fabcar/stopFabric.sh

`byfn.sh` can only remove chaincode containers and images for `mycc`. Thus `byfn.sh down`, nor a future `byfn.sh up`, on its own, does not do a complete teardown of the `fabcar` network, the suggested script does.
The functions `clearContainers` and `removeUnwantedImages` have been copied from `first-network`'s `byfn.sh` and have only been modified to address the `fabcar` chaincode instead of the `mycc` chaincode.
In order not to overload this PR, no attempts of making `byfn.sh` parameterizable in respect of the chaincode to install or to use during teardown have been made.

Added stop script to remove `fabcar` chaincode containers and images.

---

high-throughput/scripts/channel-setup.sh
high-throughput/scripts/install-chaincode.sh

Updated ports number for peers connection to match the new docker setup used in version 1.4 (first-network sample)

Fix port numbers for peers in high-throughput

---

commercial-paper/README.md

This patch fixes some typos in Commercial Paper readme.
Signed-off-by: Tatsuya Sato <Tatsuya.Sato@hal.hitachi.com>
- Documentation
Fix some typos in Commercial Paper readme
https://jira.hyperledger.org/browse/FAB-17062

[FAB-17062] Fix typos in Commercial Paper readme

---

test-network/network.sh

This patch fixes some wrong artifact names for fabric-ca in
`fabric-samples/test-network/network.sh`.
- Bug fix
Artifacts names which include `issuerPublicKey` and `issuerRevocationPublicKey`
should start with capital letters.
Due to the wrong names, some files remain even after running the command to
bring down networks using fabric-ca.
https://jira.hyperledger.org/projects/FAB/issues/FAB-17306

[FAB-17306] Fix artifact names in test-network

---

interest_rate_swaps/README.md

This is now done by the script, and does not need to be done by the end user from their GOAPTH. Updating the sample readme.

Remove references to vendoring chaincode from Interest Rate Sample readme

---

ci/install-fabric.yml

Update fabric version

---

test-network/network.sh

Add 1.x versions of Fabric to the blacklist. The test network can only run on 2.0. If run on 1.4.x, the orderer will exit due to 2.0 capabilities.
Removing unused variable from script.

Add 1.x versions of fabric to blacklisted versions

---

chaincode/fabcar/java/build.gradle

This change updates build.gradle to fabric 1.4.4.

Fixes Fabcar Java chaincode build dependency

---

chaincode/abstore/java/build.gradle
chaincode/abstore/javascript/package.json
chaincode/fabcar/java/build.gradle
chaincode/fabcar/javascript/package.json
chaincode/fabcar/typescript/package.json
chaincode/marbles02/javascript/package.json
commercial-paper/organization/digibank/application-java/pom.xml
commercial-paper/organization/digibank/contract-java/shadow-build.gradle
commercial-paper/organization/digibank/contract/package.json
commercial-paper/organization/magnetocorp/contract-java/build.gradle
commercial-paper/organization/magnetocorp/contract/package.json

NodeSDK has not been released at 2.0.0 to date

[FAB-17447] Update to 2.0.0 Libraries

---

chaincode/fabcar/go/go.mod
chaincode/fabcar/go/go.sum

[FAB-17477](http://jira.hyperledger.org/browse/FAB-17477)
Update to Go contract API version to 1.0.0

[FAB-17477] Update fabcar to use go api v1.0.0

---

commercial-paper/network-clean.sh
commercial-paper/network-starter.sh

[FAB-17457] Script correction

---

ci/azure-pipelines.yml
ci/commercialpaper-go.yml
ci/commercialpaper-java.yml
ci/commercialpaper-javascript.yml
ci/testnetwork.yml
commercial-paper/organization/digibank/digibank.sh
commercial-paper/organization/magnetocorp/magnetocorp.sh
test-network/scripts/envVar.sh

[FAB-17498] Beta Images removal, test test-network

---

test-network/addOrg3/fabric-ca/registerEnroll.sh
test-network/docker/docker-compose-e2e.yaml
test-network/docker/docker-compose-test-net.yaml
test-network/network.sh
test-network/organizations/cryptogen/crypto-config-orderer.yaml
test-network/organizations/fabric-ca/registerEnroll.sh
test-network/scripts/deployCC.sh

Removing a reference to the 2.0 beta now that the GA as been released.
Also: 
- Adding listen port to the orderer configuration
- removing the `hf.Registrar.Roles` in the registerEnroll script that serve no purpose (were a result of trial and error making the script)
- Adding localhost CSR to the orderer node so that folks have one less error to hit

Remove reference to 2.0 beta

---

test-network/docker/docker-compose-ca.yaml

The CA's are not part of the `test` docker network. So applications written and hosted on the `test` network cannot interact with the CA

Add CA's to docker test network

---

test-network/addOrg3/ccp-template.json
test-network/addOrg3/ccp-template.yaml
test-network/configtx/configtx.yaml
test-network/organizations/ccp-template.json
test-network/organizations/ccp-template.yaml
test-network/scripts/createChannel.sh
test-network/scripts/deployCC.sh

Removing a reference to solo and kafka that has since been removed from BYFN. Removing some other stray references to BYFN that were left over.

Remove solo and kafka comment from test-net configtx.yaml

---

first-network/configtx.yaml
interest_rate_swaps/network/configtx.yaml
test-network/configtx/configtx.yaml

Description
The use of Orderer.Addresses in configtx.yaml is deprecated, and Organizations.<Org>.OrdererEndpoints should be used instead. Therefore, update all the fabric-samples configtx.yaml files.
Related issues
https://jira.hyperledger.org/browse/FAB-17504
Signed-off-by: xu wu <wuxu1103@163.com>

[FAB-17504] add Organizations.<Org>.OrdererEndpoints and remove Orderer.Addresses

---

fabcar/startFabric.sh

From `REGEX="Package ID: (.*), Label: $LABEL"` To `REGEX="Package ID: ([^,]*), Label: $LABEL"`
REGEX default is "Greedy search"

fix: package seletor REGEX

---

test-network/scripts/deployCC.sh

_initLedger_ must be called instead of _init_, that does not exist.
That also keeps consistency between the "with TLS" and "withtout" TLS cases.
Signed-off-by: Jonathan Gross <woodyjon@gmail.com>

test-network chaincode deployment script: init function does not exist on fabcar

---

.gitignore
ci/azure-pipelines.yml
ci/install-fabric.yml

The current scripts download the fabric binaries and place them in `/usr/local`. Modifying the host system in CI is generally bad practice. The `bootstrap.sh` script also downloads the binaries into the root of the `fabric-samples` repo. It is good practice for us to do the same in CI. We also have several samples that make an assumption about the location of these scripts. In the future we should re evaluate these examples.

Change Download Location of Fabric Binaries

---

commercial-paper/organization/magnetocorp/application-java/pom.xml

The remote artifactory https://hyperledger.jfrog.io/hyperledger/fabric-maven contain the hyperledger dependencies but the group id was wrong.
This PR corrects the groupId to be able to retrieve it locally and process the build.

Wrong groupId on hyperledger fabric dependencies for java-application

---

fabcar/java/pom.xml
fabcar/java/src/main/java/org/example/ClientApp.java
fabcar/java/src/main/java/org/example/EnrollAdmin.java
fabcar/java/src/main/java/org/example/RegisterUser.java
fabcar/javascript/enrollAdmin.js
fabcar/javascript/invoke.js
fabcar/javascript/query.js
fabcar/javascript/registerUser.js
fabcar/networkDown.sh
fabcar/startFabric.sh
fabcar/typescript/src/enrollAdmin.ts
fabcar/typescript/src/invoke.ts
fabcar/typescript/src/query.ts
fabcar/typescript/src/registerUser.ts
test-network/network.sh
test-network/scripts/deployCC.sh

Moving fabcar from byfn to the new test network.
- Using the CAs supported natively by the test network
- Using the scripts provided by the test network and remove the chaincode deployment in `startFabric.sh`
- Change connection profile path
- user1 > appUser since user 1 is already registered with the CA
- Adding a `stopFabric.sh` script so users do not have to change directories.
Related Issues:
This update to the sample corresponds to this update to the first app tutorial: https://github.com/hyperledger/fabric/pull/522
The two should be merged together.

[FAB-17268] Move fabcar sample to test network

---

test-network/scripts/deployCC.sh

With the new Fabric contract class, you can initialize the chaincode by invoking any function, and the init will be invoked under the covers. As a result, the Init and then Invoke flow of the deployCC script is out of date, and the second invoke can be removed.
Thanks @woodyjon and @mbwhite for bringing this to my attention.

Remove redundant invoke command from test network

---

off_chain_data/blockProcessing.js

This PR replaces PR #101 which was submitted by @manish1635 and was badly mangled.
Before fix:
```
$ node blockEventListener.js
fabric-samples/off_chain_data/blockProcessing.js:53
continue();
^
SyntaxError: Unexpected token '('
at Module._compile (internal/modules/cjs/loader.js:895:18)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
at Module.load (internal/modules/cjs/loader.js:815:32)
at Function.Module._load (internal/modules/cjs/loader.js:727:14)
at Module.require (internal/modules/cjs/loader.js:852:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (fabric-samples/off_chain_data/blockEventListener.js:48:25)
at Module._compile (internal/modules/cjs/loader.js:959:30)
at Object.Module._extensions..js …
```

FAB-17419 Fix off_chain_data sample error

---

test-network/network.sh

This line in the `networkDown()` cleanup is left over from the network upgrade portion of BYFN. It can be removed from the test network.

Remove left over rm -rf command from BYFN

---

chaincode/fabcar/java/src/main/java/org/hyperledger/fabric/samples/fabcar/CarQueryResult.java
chaincode/fabcar/java/src/main/java/org/hyperledger/fabric/samples/fabcar/FabCar.java
chaincode/fabcar/java/src/test/java/org/hyperledger/fabric/samples/fabcar/FabCarTest.java

The java implementation of the fabcar example is in some cases a little bit different from the doc and other implementations like go and javascript. Some aspects are discussed [here](https://github.com/hyperledger/fabric/pull/969#discussion_r401741589)
- Index/Key has always three digits. Other implementations do not have leading zeroes
- Other implementations return the key of the record which was queried.
The key was updated to be compatible with the doc.
Query results contains the key of the record. Because it is printed very often in this tutorial.

Update java chaincode to be compatible with doc and other implementations

---

test-network/scripts/createChannel.sh
test-network/scripts/deployCC.sh
test-network/scripts/envVar.sh
test-network/scripts/org3-scripts/envVarCLI.sh
test-network/scripts/org3-scripts/step1org3.sh

The create Channel and deploy chaincode scripts contained an if statement on whether TLS was enabled for many commands
```
if [ -z "$CORE_PEER_TLS_ENABLED" -o "$CORE_PEER_TLS_ENABLED" = "false" ] ; then
```
I assume this is left over from older versions of 1.x, and from Kafka or solo consensus. Since TLS is required for RAFT and other features, I removed the TLS not enabled option.

Remove TLS = false if statement in test network

---

chaincode/abstore/java/build.gradle
chaincode/fabcar/java/build.gradle
commercial-paper/organization/digibank/application-java/pom.xml
commercial-paper/organization/digibank/application/package.json
commercial-paper/organization/digibank/contract-java/build.gradle
commercial-paper/organization/digibank/contract-java/shadow-build.gradle
commercial-paper/organization/magnetocorp/application-java/pom.xml
commercial-paper/organization/magnetocorp/application/package.json
commercial-paper/organization/magnetocorp/contract-java/build.gradle
fabcar/typescript/package.json
off_chain_data/package.json

Update application and chaincode dependencies to use v2.0 or
later versions in package.json, build.gradle, pom.xml files.

Update samples to use v2.0 or later dependencies

---

README.md
chaincode/README.md
off_chain_data/README.md

Update READMEs to improve documentation in the samples repo.
Most importantly, for download instructions, we should use the topics in the Fabric docs to capture the most recent changes. I also think users would benefit from tables that would provide more detail on each sample and include a link to the accompanying tutorial. Some of these samples and chaincode, interest rate samples = state based endorsement, abac = attribute based access control, could help users find and take advantage of these samples.

[FAB-17818] Update documetation in Fabric samples repo

---

test-network/network.sh

Currently, the test network appends the current directory to the path. `PATH=${PWD}/../bin:${PWD}:$PATH`
As @jyellick points, this is unnecessary. The tested the network on MacOS without it and it works fine.
Is there a reason why it should still be added? Is there another platform or use case where it needs to added?

Remove adding current directory to path

---

MAINTAINERS.md

Nik has been the main source of progress in the fabric-samples
repository for several months, making significant improvements with
the introduction of test-network and updates of all the different
samples around it, among other things.

Nominate Nikhil Gupta as Fabric-samples maintainer

---

chaincode/marbles_transfer/README.md
chaincode/marbles_transfer/marbles_transfer.go

Signed-off-by: Tiffany Harris <tiffany.harris@ibm.com>
Verifies asset private data matches on chain hashes 
- Add query to verifies asset properties
- Delete price records from buyer and seller private data collections
when transfer is complete
- Add 'receipt' for asset transfer

Add VerifyAssetProperties to marbles_transfer example

---

chaincode/marbles_transfer/README.md
first-network/scripts/script.sh
first-network/scripts/utils.sh
high-throughput/scripts/approve-commit-chaincode.sh
high-throughput/scripts/del-traditional.sh
high-throughput/scripts/delete-invoke.sh
high-throughput/scripts/get-invoke.sh
high-throughput/scripts/get-traditional.sh
high-throughput/scripts/many-updates-traditional.sh
high-throughput/scripts/many-updates.sh
high-throughput/scripts/prune-invoke.sh
high-throughput/scripts/update-invoke.sh
test-network/scripts/createChannel.sh
test-network/scripts/deployCC.sh

`--tls` option of the peer command does not require any argument.
On the other hand, some scripts assign the arguments.
This patch deletes the unnecessary arguments.
Also, this patch fixes a minor problem on private data tutorial instructions for base64 (Related to FAB-13777).
- https://jira.hyperledger.org/browse/FAB-17957
- https://jira.hyperledger.org/browse/FAB-6815
- https://jira.hyperledger.org/browse/FAB-13777

[FAB-17957] Delete `--tls` extra arguments from fabric-samples

---

test-network/addOrg3/fabric-ca/registerEnroll.sh
test-network/organizations/fabric-ca/registerEnroll.sh

This patch adds missing config.yaml to msp folder for user1 in test-network to make user1 work properly when using FabricCA.
- Bug fix
This patch adds missing config.yaml to msp folder for user1 in test-network to make user1 work properly when using FabricCA.
- https://jira.hyperledger.org/browse/FAB-18020

[FAB-18020] Add config.yaml to msp folder for User1 in test-network

---

asset-transfer-basic/chaincode-go/go.mod

* Fixing go.mod module path for `asset-transfer-basic` chaincode-go to point at the correct directory.

Fix go mod for chaincode-go

---

chaincode/fabcar/java/build.gradle
chaincode/fabcar/java/gradle/wrapper/gradle-wrapper.properties

- Update gradle version
- Switch to application plugin
(cc is started as an app not a lib, and java-library-distribution
is still incubating)
- make sure tests and coverage checks are run before installDist

Update fabcar java sample build

---

ci/azure-pipelines.yml
test-network/addOrg3/docker/docker-compose-couch-org3.yaml
test-network/docker/docker-compose-couch.yaml

Fabric 2.2 removes official support for CouchDB 2.x.
The migration to 3.1 was to address fsync issues
in the underlying storage implementation in Couch.
This change moves to CouchDB 3.1 which requires the
user to now set an admin identity at startup.

Use Official CouchDB 3.1 Image

---

interest_rate_swaps/network/docker-compose.yaml
test-network/addOrg3/docker/docker-compose-org3.yaml
test-network/docker/docker-compose-test-net.yaml

In Fabric v2.2, the gossip defaults are changed to make
peers org leaders instead of using leader election.
This change removes the config from the samples, so that
the samples simply inherit the new peer defaults.
This will simplify the sample configuration.

Remove gossip leader election config from samples

---

ci/templates/commercial-paper/azure-pipelines-go.yml
ci/templates/commercial-paper/azure-pipelines-java.yml
ci/templates/commercial-paper/azure-pipelines-javascript.yml

Update the commercial paper tests to use the test network certificate authorities and the `enrollUser.js` file, so we can test the same path used by the tutorial.
Also updating the go contract test, since it was testing the Java contract for some reason.

Update tests for commercial paper

---

chaincode/fabcar/java/src/main/java/org/hyperledger/fabric/samples/fabcar/FabCar.java
chaincode/fabcar/java/src/test/java/org/hyperledger/fabric/samples/fabcar/FabCarTest.java

Java chaincode still does not support open ended range queries

Fix java fabcar queryAllCars

---

asset-transfer-secured-agreement/chaincode-go/asset_transfer.go
asset-transfer-secured-agreement/chaincode-go/asset_transfer_queries.go

Rewrites the chaincode in idiomatic Go and cleans up
the general implementation.
A future commit should push the chaincode logic itself
into a separate package as chaincode cannot be tested
when the logic is part of the main package.

Refactor Asset Secured Chaincode Into Idiomatic Go

---

asset-transfer-ledger-queries/chaincode-go/asset_transfer_ledger_chaincode.go

Rewrites the chaincode in idiomatic Go and cleans up
the general implementation.
A future commit should push the chaincode logic itself
into a separate package as chaincode cannot be tested
when the logic is part of the main package.

Refactor Asset Query Chaincode Into Idiomatic Go

---

ci/templates/test-network/azure-pipelines.yml
fabcar/startFabric.sh
test-network/.gitignore
test-network/README.md
test-network/network.sh
test-network/scripts/deployCC.sh
test-network/scripts/envVar.sh
test-network/scripts/org3-scripts/envVarCLI.sh

options on the network script to deploy chaincode
-ccn The name to be used as the deployed name and used as
the short name of known chaincodes when the -ccp is not included.
known short names
'basic' - asset-transfer-basic
'secure' - asset-transfer-secured-agreement
'ledger' - asset-transfer-ledger-queries
'private' - asset-transfer-private-data
-ccl the language of the chaincode
-ccv the version
-ccp [optional] the path to the chaincode, when provided
the -ccn will be the deployed name
-cci [optional] the chaincode function to call during deployment
that will perform an initialization of the channel state
required for this chaincode
Signed-off-by: Bret Harrison <beharrison@nc.rr.com>

Allow install of a chaincode

---

asset-transfer-basic/chaincode-go/chaincode/smartcontract.go
asset-transfer-basic/chaincode-go/chaincode/smartcontract_test.go

There was no need for GetAllAssets to return a custom type, it can simple return an array of all assets.

Remove QueryResult Type

---

test-network/network.sh
test-network/scripts/deployCC.sh

Add endorsement policy and collection configuration parameters to the deployCC script.
Also add let users know if they provide a bad chaincode path, or if the language and sample are not yet available

Add endorsement policy to chaincode deployment script

---

test-network/organizations/fabric-ca/registerEnroll.sh

Using `-p` in `mkdir`. It prevents to output error if directories already exist.

use mkdir -p for create directories

---

test-network/scripts/deployCC.sh

- The help text offers to deploy the `secured` smart contract, while the script requires `secure`. Going with secured as the better name
- Correct the text that is printed if you select the ledger query smart contract

Fix bugs in deployCC script

---

test-network/network.sh

We delete folders and files locally on the host system today. If the user is not a super user the files can't be deleted as they are created by a root user in the containers. This change uses busybox to perform the deletions instead so a root user can remove them.

Use Busybox to Remove Files and Folders

---

interest_rate_swaps/README.md
interest_rate_swaps/network/scripts/script.sh

Corrected swap JSON payload so that the JSON object can be unmarshalled properly
Signed-off-by: Aldred Benedict <aldred@sg.ibm.com>

Corrected swap JSON payload in interest_rate_swaps example

---

asset-transfer-basic/chaincode-go/chaincode/smartcontract.go

Although the current code works thanks to Go being quite
forgiving when it comes to pointers, it doesn't exhibit
the best coding style. This patch addresses this.

Improve unmarshalling in asset-transfer-basic Go cc

---

README.md

Update samples documentation to let people know that they should use the basic asset transfer sample as an intro, instead of Fabcar.
Update the asset transfer series table for the new languages

Update samples readme for fabcar deprecation, new langagues

---

asset-transfer-ledger-queries/chaincode-go/asset_transfer_ledger_chaincode.go

The InitLedger was not writing the composite key for the color index.
Therefore TransferAssetByColor was not working.
Now InitLedger will call CreateAsset which creates both the asset
and the color index entry.

Fix ledger queries chaincode-go InitLedger

---

asset-transfer-basic/chaincode-external/sampleBuilder/bin/detect

This change makes the way the type property is extracted from the
metadata.json file much more robust, and therefore sets a better
example.

Improve basic asset transfer external chaincode detect script

---

asset-transfer-private-data/application-javascript/app.js
asset-transfer-private-data/chaincode-go/private_asset_queries.go
ci/scripts/run-test-network-private.sh

Re-enable CI tests for asset-transfer-private-data JavaScript application.
Also re-add the error when private asset details are not found in the collection,
so that the CLI instructions work as desired, and to demonstrate error
handing in the client application.

Re-enable CI tests for asset-transfer-private-data JS app

---

README.md

The links in the README redirect to a 404. The valid documentation links point to `release-2.2` instead of `master`.
Signed-off-by: Rijul Aggarwal <rijul.aggarwal@ibm.com>

Readme links fix - point to latest

---

test-network/network.sh

network.sh still had reference to fabcar for artifact removal.  This change updates artifact removal to reference the new basic sample.

Update script artifacts removal to reference basic.tar.gz and remove fabcar

---

test-network/network.sh

In the past, there have been committed to change the output method of help messages from "echo" to "println”.
Dou to that change, network.sh not shown help messages correctly.
When changing the method of output help message "echo" to "println", the message format should be fixed.
Signed-off-by: ikegawa-koshi <koshi.ikegawa.mf@hitachi.com>

Fix help messages

---

test-network/network.sh

If the registerEnroll script runs before the CA is fully stood up, the script fails. Currently, there is a 10 second waiting period to guarantee that the CAs are up before the enroll commands are issued. This was always a temporary hack, but it is still there.
This removes the 10 second waiting period and instead waits until the CA container creates the required TLS certificate. It's much shorter than 10 seconds, and should speed up the tutorials and the tests (more and more of which use the CA's). If you have a better idea, feel free to let me know.

Replace ca waiting period

---

test-network/configtx/configtx.yaml

Signed-off-by: 暾暾 <631078133@qq.com>

Fixed sdk connection bugs "SendTransaction failed: orderers is nil", make it fit the "entityMatchers" way.

---

test-network/network.sh
test-network/scriptUtils.sh
test-network/scripts/deployCC.sh

Moves the help text to the scriptUtils, and create mode specific help text.
For example:
```
Usage: 
network.sh deployCC [Flags]
Flags:
-c <channel name> - Name of channel to deploy chaincode to
-ccn <name> - Chaincode name. This flag can be used to deploy one of the asset transfer samples to a channel. Sample options: basic (default),ledger, private, sbe, secured
-ccl <language> - Programming language of chaincode to deploy: go (default), java, javascript, typescript
-ccv <version>  - Chaincode version. 1.0 (default), v2, version3.x, etc
-ccs <sequence>  - Chaincode definition sequence. Must be an integer, 1 (default), 2, 3, etc
-ccp <path>  - (Optional) File path to the chaincode. When provided, the -ccn flag will be used only for the chaincode name.
-ccep <policy>  - (Optional) …
```

Add mode specific help text

---

token-utxo/README.md

The user's PATH must be set on the first use of Terminal 2 for the
call to the fabric-ca-client command to succeed. The current README
only sets it later. This fix changes that.

Fix token-utxo-based README terminal 2 setup

---

token-account-based/README.md

The user's PATH must be set on the first use of Terminal 2 for the
call to the fabric-ca-client command to succeed. The current README
only sets it later. This fix changes that.

Fix token-account-based README terminal 2 setup

---

asset-transfer-basic/chaincode-external/README.md

Went through this doc today and was surprised that their was no link to the relevant doc

Include link to external chaincode builder doc

---

commercial-paper/organization/digibank/digibank.sh
commercial-paper/organization/magnetocorp/magnetocorp.sh

The current scripts given to setup the user environment do not work
on Mac:
$ . ./magnetocorp.sh
-bash: cd: /Users/lehors/Projects/Go/src/github.com/hyperledger/fabric-samples/commercial-paper/organization/magnetocorp
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed./../../../test-network: No such file or directory
-bash: ./scripts/envVar.sh: No such file or directory
[...truncated...]
export FABRIC_CFG_PATH="/Users/lehors/Projects/Go/src/github.com/hyperledger/fabric-samples/commercial-paper/organization/magnetocorp"
export PATH="/Users/lehors/Projects/Go/src/github.com/hyperledger/fabric-samples/commercial-paper/organization/magnetocorp"
export PEER_PARMS=""
Saving session...
Saving session...
The session history related output …

Fix commercial paper org scripts

---

token-utxo/chaincode-go/chaincode/token_contract.go

Added check to avoid double spent in token-utxo chaincode
In the transfer function it was possible to pass the same utxo more than once in the array of input utxos without any error. Making it possible to spend the same utxo more than once in the same transaction and like this create more tokens than minted. To fix this I changed the array that was used to store the input utxo states to a map and so utxos were stored in the map by there key, which made it possible to know if a key and so a utxo had already been used.
I tested this by setting up the test-network, deploying the token-utxo chaincode with my fix, minting a utxo and trying to spent this utxo more than once in the same transaction, which was not possible anymore. It can only be spent one time anymore with this fix.

Avoid double spent in token-utxo chaincode

---

token-erc-20/README.md

Update ERC-20 readme to indicate the new contract name
and add TransferFrom tutorial for Go chaincode.

Update ERC-20 readme

---

commercial-paper/README.md

This is a pet peeve of mine: 'here' is a very poor choice for a link
anchor.
See https://lehors.wordpress.com/2009/01/29/linking-the-proper-way/

Fix link anchor "here" in sample README

---

test-network/docker/docker-compose-test-net.yaml

When going through the new channel participation tutorial, I realize that we do not mount the configuration file in the test network containers, instead using the files that are inside the container. In addition to not being best practice, it makes it hard to update the containers.

Mount configuration files in the test network

---

test-network/docker/docker-compose-test-net.yaml

Reverts hyperledger/fabric-samples#376
The change will break things if you use the Fabric download script (which would currently give you 2.3 config) and then try to run the v2.2 images using the test-network -i flag. Unfortunately the orderer crashes if there is config it doesn't understand. While that's not good, regardless it is always best to run images with the same version of the config, that's why the version-specific images have the version-specific config built in. The test-network should use the config built into the images as the starting defaults so that things always work by default.
@nikhil550 @lehors FYI

Revert "Mount configuration files in the test network"

---

asset-transfer-secured-agreement/application-javascript/app.js

This fix corrects the pathing in the application operational instructions where some paths in the comments incorrectly pointed to the sbe sample and not the secured-agreement sample.
Signed-off-by: Chris Gabriel <chris@hyperchainlabs.com>

Fix path in app.js operational instruction comment section

---

auction/README.md
high-throughput/startFabric.sh
token-erc-20/README.md
token-utxo/README.md

With https://github.com/hyperledger/fabric-samples/pull/390 requiring the -ccl path, we need to add it to some samples that used the go default
Signed-off-by: Nikhil Gupta <nikhilgupta@macbook-air.lan>

Add go smart contract language to deploy commands

---

commercial-paper/organization/digibank/configuration/cli/docker-compose.yml
commercial-paper/organization/magnetocorp/configuration/cli/docker-compose.yml
interest_rate_swaps/network/docker-compose.yaml
test-network/addOrg3/docker/docker-compose-org3.yaml
test-network/docker/docker-compose-test-net.yaml

Instead of mounting the entire `/var/run` directory explicitly mount the unix socket. Mounting the entire directory causes issues with future versions of Docker on some platforms.

Explicitly Mount the Docker Unix Socket

---

test-network/addOrg3/fabric-ca/registerEnroll.sh
test-network/organizations/fabric-ca/registerEnroll.sh

There has been a lot of cosmetic updates of the test network script. As part of that, I thought it was time to do some cleanup of the register enroll scripts. This PR
- removes commented out lines.
- removes the unnecessary import of the script utils, which are imported by the main scripts.
- removing unnecessary mkdir commands. The enroll commands generate most of the directories that are required.

Cleanup of register/enroll script

---

commercial-paper/network-starter.sh

Fix usage of `*` which was treated as literal symbol instead of wildcard.

Fix crypto materials copy in commercial-paper network-starter

---

test-network/addOrg3/.env
test-network/addOrg3/docker/docker-compose-ca-org3.yaml
test-network/addOrg3/docker/docker-compose-couch-org3.yaml
test-network/addOrg3/docker/docker-compose-org3.yaml
test-network/docker/.env
test-network/docker/docker-compose-ca.yaml
test-network/docker/docker-compose-couch.yaml
test-network/docker/docker-compose-test-net.yaml

There have been lots of changes and quirks with the docker-compose .env file, this change removes the file and explicitly creates and assigns the networks in the compose yaml files.
As a sidenote, this is why the functionality changed, they changed the default location where `.env` was read from, CI recently upgraded to a version of compose that had this change: https://github.com/docker/docker.github.io/commit/7c8c667165f2c275b0294e4ddd4e74761bd930e7#diff-4b87475dd0f3c1791c56c3b5f231860a7e4ee3a2a380ba86a0bc27af64296e56
Signed-off-by: Brett Logan <lindluni@github.com>

Remove .env Files and Explicitly Name Network

---

test-network/addOrg3/addOrg3.sh
test-network/addOrg3/docker/docker-compose-ca-org3.yaml
test-network/addOrg3/docker/docker-compose-couch-org3.yaml
test-network/addOrg3/docker/docker-compose-org3.yaml
test-network/docker/docker-compose-ca.yaml
test-network/docker/docker-compose-couch.yaml
test-network/docker/docker-compose-test-net.yaml
test-network/network.sh

Add a service label to all containers launched by compose. This allows us to filter on the label for removing running containers.
Use filtering for querying running containers and images to make sure we only target the containers and images we want to remove.
Removes the `OS_ARCH` var as it was unused.

Add Service Labels and Cleanup Using Standard Tools  and Remove Unused Vars

---

test-network/docker/docker-compose-ca.yaml
test-network/docker/docker-compose-couch.yaml
test-network/docker/docker-compose-test-net.yaml

When i tried to set up a new test network, i got the error
`ERROR: The Compose file './docker/docker-compose-ca.yaml' is invalid because:
networks.test value Additional properties are not allowed ('name' was unexpected)`
I think the reason is that the 'name' is only available after version 2.1 according to the [docker docs](https://docs.docker.com/compose/compose-file/compose-file-v2/#name-1). So I change the version of docker compose file to 2.4, just like the example in the docker docs. Finally, everything worked fine.

Change docker compose file version

---

asset-transfer-basic/chaincode-external/README.md

Some updates to the external chaincode readme for readability and clarity. These updates make it less likely that users will forget to make the required update the .env file like I did. Also
- updating the name of the new docker compose network
- changing the link to the correct tutorial
- adding the path to the required configuration file
- Letting users know they no longer need mount docker.sock in the peer container

Updates to external chaincode readme

---

token-erc-20/chaincode-go/chaincode/token_contract.go

Lowercase fields of a struct in Go are not exported. Therefore, the JSON marshalled from the `event` struct creates an empty object. I capitalized the first letters of the fields and added JSON tags so that the key name of the fields remain the same.
Signed-off-by: Baran Kılıç <baran.kilic@boun.edu.tr>

Fix empty event in token-erc-20 example

---

token-erc-20/chaincode-go/chaincode/token_contract.go
token-erc-20/chaincode-javascript/lib/tokenERC20.js
token-erc-20/chaincode-javascript/test/tokenERC20.test.js

Using the ERC-20 sample, you can submit a transfer to and from
the same account. Because the code doesn't handle this, it ends
up minting new tokens into that account.
The correct behaviour is not specified by the ERC-20 specification,
although the OpenZeppelin implementation seems to permit it.
IMO we should just block it with an error because I can't see a use
case for allowing it and it is most likely a user error.
Signed-off-by: Simon Stone <sstone1@uk.ibm.com>

Stop ERC-20 transfer bug when to/from accounts are the same

---

chaincode/abstore/javascript/abstore.js

Standard validation for numbers does not work.
if (typeof parseInt(Aval) !== 'number' || typeof parseInt(Bval) !== 'number') { return shim.error('Expecting integer value for asset holding'); }
Good:
if (isNaN(parseInt(Aval)) || isNaN(parseInt(Bval))) { return shim.error('Expecting integer value for asset holding'); }
Otherwise contract accepts no number values as below:
Signed-off-by: Michał Mirończuk <michalmironczuk1@gmail.com>

abstore smart contract - Fixed Aval and Bval validation

---

SECURITY.md
asset-transfer-basic/chaincode-javascript/test/assetTransfer.test.js
asset-transfer-events/chaincode-javascript/test/assetTransferEvents.test.js
asset-transfer-ledger-queries/chaincode-javascript/lib/asset_transfer_ledger_chaincode.js
commercial-paper/organization/digibank/contract/lib/queries.js
commercial-paper/organization/magnetocorp/application/cpListener.js
commercial-paper/organization/magnetocorp/contract/lib/queries.js
token-erc-20/chaincode-javascript/index.js
token-erc-20/chaincode-javascript/lib/tokenERC20.js
token-erc-20/chaincode-javascript/test/tokenERC20.test.js

Fix link in SECURITY file, and add missing copyright and license notices.
To check, run: repolinter --rulesetUrl https://github.com/hyperledger-labs/hyperledger-community-management-tools/raw/main/repo_structure/repolint.json

Fix repolinter failures

---

test-network/docker/docker-compose-test-net.yaml

Peers and Orderers by default disable Go pprof profiling, however test
network was enabling pprof in peers by default. As a good practice,
pprof should be disabled by default and only enabled when needed
for debug profiling.

Disable Go pprof profiling in test network

---

asset-transfer-basic/chaincode-javascript/lib/assetTransfer.js

- In CreateAsset, await was never called on putState causing issues
especially with tools such as caliper and is not correct practice.
Unfortunately all the other examples use `return` which works but is
actually not the idiomatic way of handling promises, so here await is
chosen rather than return

Correct Javascript Chaincode

---

off_chain_data/blockEventListener.js

The off_chain_data sample fails to put data to the off-chain
database. The application does not read fetched blocks because
it uses the old interface of `addBlockListener()` to handle
block events.
This PR fixes the application to use the latest block listener
and build the off-chain database.
Signed-off-by: Yuki Kondo <yuki.kondo.ob@hitachi.com>

Fix off_chain_data to put data to off-chain database

---

asset-transfer-basic/chaincode-javascript/lib/assetTransfer.js
asset-transfer-basic/chaincode-typescript/src/assetTransfer.ts

The Golang and Java sample chaincode returned an error when trying to create an asset which already exists
JavaScript and TypeScript samples should now do the same

Update CreateAsset txn in basic js and ts sample

---

test-network/addOrg3/addOrg3.sh
test-network/addOrg3/docker/docker-compose-org3.yaml
test-network/docker/docker-compose-test-net.yaml
test-network/network.sh

Docker version 20.10 support rootless mode. That features
changes a mount path of docker.sock.
This PR loads a mount path from DOCKER_HOST environment,
and if not set, a mount path will be /var/run/docker.sock
FAB-18481
Signed-off-by: Nao Nishijima <nao.nishijima.xt@hitachi.com>

Support docker.sock in rootless mode

---

test-network/addOrg3/docker/docker-compose-ca-org3.yaml
test-network/addOrg3/docker/docker-compose-couch-org3.yaml
test-network/addOrg3/docker/docker-compose-org3.yaml

Following the instructions to set an organization 3, the docker-compose file (test-network/addOrg3/docker/docker-compose-org3.yaml) was invalid because it didn't accept additional properties in the network declaration (test_network) with docker-compose version 2. I was able to solve the problem by setting the version to 2.4.

change docker-compose version from 2 to 2.4  on folder addOrg3/docker

---

test-network/.env
test-network/addOrg3/.env
test-network/addOrg3/docker/docker-compose-ca-org3.yaml
test-network/addOrg3/docker/docker-compose-couch-org3.yaml
test-network/addOrg3/docker/docker-compose-org3.yaml
test-network/docker/docker-compose-ca.yaml
test-network/docker/docker-compose-test-net.yaml

Backport from main to release-2.2.
There have been lots of changes and quirks with the
docker-compose .env file, this change removes the file
and explicitly creates and assigns the networks in the
compose yaml files.
Signed-off-by: Brett Logan <lindluni@github.com>

Remove .env Files and Explicitly Name Network (#417)

---

asset-transfer-basic/chaincode-java/build.gradle
asset-transfer-events/chaincode-java/build.gradle
asset-transfer-private-data/chaincode-java/build.gradle
asset-transfer-sbe/chaincode-java/build.gradle

Json libraries were pulled into the project in fabric-chaincode-shim:2.+  BUT - they were declared in the project scope as compileOnly and/or testImplementation.
Fabric-chaincode-shim used to (2.2.3) declare the json dependency with scope compile. In 2.3.1 and 2.4.0-beta the transitive dependencies are declared as runtime, which means they won’t be available to the compiler.
Changed all java dependecies from 
"compileOnly 'org.hyperledger.fabric-chaincode-java:fabric-chaincode-shim:2.+'"
to
"implementation 'org.hyperledger.fabric-chaincode-java:fabric-chaincode-shim:2.+'
implementation 'org.json:json:+'"
Additionally declaration for transient dependency 'org.hyperledger.fabric.protos.common' was added
P.S. dependencies were already changed from compile only to implementatio in PR …

Updated dependencies for Json and fabric-chaincode-shim:2.+ in java samples

---

first-network/base/docker-compose-base.yaml

Explicitly mount docker.sock on the old first network sample. The sample is deprecated. However, this update will allow the sample to run on MacOS and allow me and others to run migration tests.
'
Signed-off-by: Nikhil Gupta <ngupta@triplepointliquidity.com>

Update first-network to explicity mount docker unit socket

---

test-network/docker/docker-compose-test-net.yaml

If ORDERER_KAFKA_VERBOSE is true, the output of /logspec will contain
the following kafka information even if it is raft orderer.
{"spec":"orderer.consensus.kafka.sarama=debug:info"}
This PR deletes environment valiable for kafka in docker-compose.
Signed-off-by: Nao Nishijima <nao.nishijima.xt@hitachi.com>

Fix: logspec output

---

test-network-nano-bash/peer1.sh
test-network-nano-bash/peer2.sh
test-network-nano-bash/peer3.sh
test-network-nano-bash/peer4.sh

CHAINCODEADDRESS is set to host.docker.internal which is
only available in MAC and Windows environments.
For that reason, it cannot launch chaincode on Linux.
This PR sets CHAINCODEADDRESS to 127.0.0.1 instead of
host.docker.internal.
Signed-off-by: Nao Nishijima <nao.nishijima.xt@hitachi.com>

Fix: Cannot launch chaincode in nano bash in Linux

---

asset-transfer-basic/chaincode-javascript/package.json
asset-transfer-basic/chaincode-typescript/package.json
asset-transfer-basic/chaincode-typescript/src/assetTransfer.ts
asset-transfer-basic/chaincode-typescript/tsconfig.json

The latest version (2.1.2) of sort-keys-recursive adds TypeScript typing, which includes export default function.
This change has caused the TS2349 type error.
This patch modifies the import form in assetTransfer.ts to fix the error.
The example of error logs is:
```javascript
github.com/fabric-samples/asset-transfer-basic/chaincode-typescript (main *)$ npm run build
> asset-transfer-basic@1.0.0 build /home/ubuntu/workspace/src/github.com/fabric-samples/asset-transfer-basic/chaincode-typescript
> tsc
src/assetTransfer.ts:66:69 - error TS2349: This expression is not callable.
Type 'typeof import("sort-keys-recursive")' has no call signatures.
66             await ctx.stub.putState(asset.ID, Buffer.from(stringify(sortKeysRecursive(asset))));
~~~~~~~~~~~~~~~~~
src/assetTransfer.ts:87:59 - …
```

Fix type error when using the latest sort-keys-recursive

---

test-network-k8s/docs/TEST_NETWORK.md
test-network-k8s/kube/org0/org0-admin-cli.yaml
test-network-k8s/kube/org0/org0-ecert-ca.yaml
test-network-k8s/kube/org0/org0-orderer1.yaml
test-network-k8s/kube/org0/org0-orderer2.yaml
test-network-k8s/kube/org0/org0-orderer3.yaml
test-network-k8s/kube/org0/org0-tls-ca.yaml
test-network-k8s/kube/org1/org1-admin-cli.yaml
test-network-k8s/kube/org1/org1-ecert-ca.yaml
test-network-k8s/kube/org1/org1-peer1.yaml
test-network-k8s/kube/org1/org1-peer2.yaml
test-network-k8s/kube/org1/org1-tls-ca.yaml
test-network-k8s/kube/org2/org2-admin-cli.yaml
test-network-k8s/kube/org2/org2-ecert-ca.yaml
test-network-k8s/kube/org2/org2-peer1.yaml
test-network-k8s/kube/org2/org2-peer2.yaml
test-network-k8s/kube/org2/org2-tls-ca.yaml
test-network-k8s/network
test-network-k8s/scripts/fabric_CAs.sh
test-network-k8s/scripts/kind.sh
test-network-k8s/scripts/test_network.sh

This PR addresses a compromise for development workflows requiring different patterns for loading images into the KIND / kubernetes cluster. 
- For casual / default usage, the docker images are loaded from the public container registries (docker.io and ghcr.io)
- For developers with network issues connecting to public registries, this PR allows for an offline "pull" and stage to the KIND control plane: 
```
export TEST_NETWORK_STAGE_DOCKER_IMAGES=true
./network kind     # << this will pull from the public repos, and run kind load docker-image ...  
./network up 
```
- For test/development of the CI latest build outputs, the container registry and revision can be overridden: 
```
export TEST_NETWORK_FABRIC_VERSION=amd64-latest 
export TEST_NETWORK_FABRIC_CA_VERSION=amd64-latest 
export …
```

Add an option to stage docker images locally to KIND

---

ci/azure-pipelines.yml

Several Fabric projects have updated their supported node versions and 16.x is the active LTS version

Update node version in CI

---

MAINTAINERS.md

Several fabric-samples maintainers have moved on to other projects.
See maintainer policies at
https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#becoming-a-maintainer

Retire dormant maintainers

---

MAINTAINERS.md

Josh has been helping to update samples for the Kubernetes age.
He has contributed the test-network-k8s sample and has been active in
managing fabric-samples issues. Let's welcome Josh
as a fabric-samples maintainer!

Nominate Josh Kneubuhl as fabric-samples maintainer

---

test-network-k8s/docs/HIGH_AVAILABILITY.md
test-network-k8s/kube/org1/org1-peer1.yaml
test-network-k8s/kube/org1/org1-peer2.yaml
test-network-k8s/kube/org2/org2-peer1.yaml
test-network-k8s/kube/org2/org2-peer2.yaml
test-network-k8s/scripts/application_connection.sh
test-network-k8s/scripts/chaincode.sh
test-network-k8s/scripts/kind.sh
test-network-k8s/scripts/test_network.sh

- Add a new label to each peer to mark which org it is in
- Create new service per org, that matches this label - so the service can pick from one of multiple pods
- Update the kubeproxy to give more choice of ha stratergies
- Update the application configmaps and samples to refer to this new service rather than specific peers

Setup basic HA features for the Peers

---

test-network-k8s/docs/KUBERNETES.md
test-network-k8s/network
test-network-k8s/scripts/chaincode.sh
test-network-k8s/scripts/utils.sh

The chaincode installation script had an error that was masking the lack of `shasum` on an end-user's machine.  This made it really hard to pick out the root cause of a downstream error.
This PR addresses the first part / root cause of Issue #511, which can be closed after this PR lands. 
This snippet will not crash with error.  $? is set to the return value of the `local` command.  
```
set -o errexit 
local foo=$(broken-command | tr -s ' ' | cut -d ' ' -f 1)
```
This snippet will error when `broken-command` terminates with a nonzero exit code: 
```
set -o errexit 
foo=$(broken-command | ...)
```

Address Issue #511 with docs and better error handling

---

test-network-k8s/docs/README.md

Update test-network-k8s readme with High Availability doc link.

Update test-network-k8s readme with High Availability doc link

---

test-network/docker/docker-compose-test-net.yaml

Extend test network to support prometheus/grafana performances framework. Fixes hyperledger/fabric-test#347

---

test-network-k8s/chaincode/asset-transfer-basic/connection.json
test-network-k8s/chaincode/asset-transfer-basic/metadata.json
test-network-k8s/config/org1/core.yaml
test-network-k8s/config/org2/core.yaml
test-network-k8s/docs/TEST_NETWORK.md
test-network-k8s/kube/org1/org1-cc-template.yaml
test-network-k8s/kube/org1/org1-peer1.yaml
test-network-k8s/kube/org1/org1-peer2.yaml
test-network-k8s/kube/org2/org2-peer1.yaml
test-network-k8s/kube/org2/org2-peer2.yaml
test-network-k8s/network
test-network-k8s/scripts/chaincode.sh
test-network-k8s/scripts/kind.sh
test-network/scripts/deployCC.sh

Using the variant of the peer's docker container from https://github.com/hyperledger/fabric/pull/2990  this PR adapts the K8S deployment to use this inbuilt chaincode builder.
- creates two deployments of the chaincode for each peer
- uses the builders ability to template the fields in the connection.json

Adding examples of CCAAS and support into the test-network-k8s

---

test-network/addOrg3/addOrg3.sh
test-network/network.sh

There are no argument after `-verbose`. So, it should not run `shift`.
If `-verbose` is not latest parameter, it will throw errro.

Fix: remove `shift` after `-verbose` 

---

asset-transfer-basic/application-java/build.gradle
asset-transfer-basic/chaincode-java/build.gradle
asset-transfer-events/chaincode-java/build.gradle
asset-transfer-ledger-queries/application-java/build.gradle
asset-transfer-private-data/chaincode-java/build.gradle
asset-transfer-sbe/chaincode-java/build.gradle
chaincode/abstore/java/build.gradle
chaincode/fabcar/java/build.gradle
commercial-paper/organization/digibank/contract-java/build.gradle
commercial-paper/organization/digibank/contract-java/shadow-build.gradle
commercial-paper/organization/magnetocorp/contract-java/build.gradle

JCenter is deprecated, can no longer be published to, and is scheduled for removal. It is now causing build failures. Replace with Maven Central.
Also remove mavenLocal() as this is not recommended practice:
https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:case-for-maven-local
Note that Jitpack still needs to be included as a package repository for Java chaincode since it has dependencies on an old version of com.github.everit-org.json-schema:org.everit.json.schema that is only published there.

Remove JCenter as a Gradle package repository

---

balance-transfer/app/query.js

This bug can lead to users can't change target peer to send query operations.

fix a bug in function [getBlockByNumber]

---

asset-transfer-events/application-gateway-go/app.go
asset-transfer-events/application-gateway-go/connect.go
asset-transfer-events/application-gateway-go/go.mod
asset-transfer-events/application-gateway-go/go.sum
ci/scripts/run-test-network-events.sh

Split boiler-plate connection code into a separate file since the basic sample already covers this aspect. The `app.go` file now only presents the main application code, making it much easier for readers to view.
Also changed the event replay code to use a different style of reading from the real-time eventing example, demonstrating the use of timeouts while reading events we expect to arrive quickly, and avoiding any possibility of the main application execution hanging indefinitely.

Refactor of asset transfer events Go sample for Fabric Gateway

---

asset-transfer-events/README.md

Fenced code blocks within a list were at the wrong level if indentation and so logically terminated the list.

Fix markdown logical structure in asset-transfer-events/README.md

---

test-network/CHAINCODE_AS_A_SERVICE_TUTORIAL.md

This fixes several typos and more importantly add an instruction to
set FABRIC_CFG_PATH without which the peer command fails.

Fix CHAINCODE_AS_A_SERVICE_TUTORIAL.md

---

test-network/prometheus-grafana/grafana/provisioning/dashboards/hlf-performances.json

- removed unused overrides
- addressed issue using $__interval which doesn't work as well as $interval
- addressed issue where multiple channels may not give correct output

further grafana dashboard improvements

---

test-network/docker/docker-compose-test-net.yaml

Ports for the operations endpoint seems different between the main branch and the 2.2 branch... need to sync so that consumer code can reference is consistently between releases.
Signed-off-by: Varad Ramamoorthy <varad@us.ibm.com>

sync ports for operations endpoint with main

---

test-network/network.sh

The network.sh is dependent on being executed from the test-network directory.
This PR makes it a little more tolerant, and will add a bin directory based on the location of the script - not just the PWD

Make network.sh more tolerant

---

asset-transfer-basic/application-gateway-typescript/src/app.ts
ci/azure-pipelines.yml
ci/scripts/run-k8s-test-network-basic.sh
ci/templates/install-k8s-deps.yml
test-network-k8s/scripts/test_network.sh

This PR adds a CI test case to run an E2E validation of the basic-asset-transfer chaincode and Gateway application on the Kubernetes Test Network. This suite exercise only ONE test case, primarily as an exercise in validating the mechanics of running the Kube Test Network on an Azure image. After the mechanics of running on Azure have been worked out, additional tests can follow, both for additional Fabric routines (e.g. Commercial Paper) and new container orchestration runtimes (e.g. containerd / podman / nerdctl / etc.)
The suite runs a complete E2E, including:
- Creates a KIND Kubernetes cluster and Nginx ingress controller.
- Configures the Kubernetes Test Network (3 org: 2x peers/org + 3x orderers) using JFrog / STABLE tag Fabric images.
- Compiles and deploys …

Run a basic-asset-transfer CI test on Kubernetes

---

test-network-k8s/kube/fabric-rest-sample.yaml
test-network-k8s/kube/org1/org1-peer1.yaml
test-network-k8s/kube/org1/org1-peer2.yaml
test-network-k8s/kube/org2/org2-peer1.yaml
test-network-k8s/kube/org2/org2-peer2.yaml
test-network-k8s/scripts/ccp-template.json

**Signed-off-by:** Charalarg <charalarg@gmail.com>
**Type of change:**
- New feature
- Bug fix
**Description:**
With these changes applications use the gateway-svc services in order to establish connection with any available peer on each organization rather than connecting manually to peer1. 
The service names need also to be added as dnsName in each peer TLS certificate configuration.
**Resolves:** #635

test-network-k8s: High availability on application connection profiles 

---

test-network/addOrg3/docker/docker-compose-ca-org3.yaml
test-network/addOrg3/docker/docker-compose-couch-org3.yaml
test-network/addOrg3/docker/docker-compose-org3.yaml
test-network/docker/docker-compose-ca.yaml
test-network/docker/docker-compose-couch.yaml
test-network/docker/docker-compose-test-net.yaml

Earlier compose version was giving a property error when running the [fabric-samples/test-network/network.sh](https://github.com/hyperledger/fabric-samples/blob/main/test-network/network.sh) script.
Docker Compose Documentation says that the property [networks:name](https://docs.docker.com/compose/compose-file/compose-file-v2/#name-1) was added in [v2.1](https://docs.docker.com/compose/compose-file/compose-versioning/#version-21) file format.
Signed-off-by: kaushikkumarbora <kaushikkumarbora@gmail.com>

fix docker compose version 2 -> 2.1

---

test-network-k8s/docs/KUBERNETES.md
test-network-k8s/docs/TEST_NETWORK.md
test-network-k8s/network

Instead of using the Fabric and Fabric CA three digit version (2.4.3),
utilize the two digit version (2.4).
Each time a Fabric/FabricCA release is pushed to dockerhub the two digit version tag is updated.
This approach simplifies maintenance so that scripts don't have to be updated for every
third digit release.
Apologies that the end of line character got updated in the IDE... the important change is in `test-network-k8s/network` file.

Update test-network-k8s to use two digit version

---

ci/azure-pipelines.yml
ci/scripts/shellcheck.sh
test-network-nano-bash/generate_artifacts.sh
test-network-nano-bash/orderer1.sh
test-network-nano-bash/orderer2.sh
test-network-nano-bash/orderer3.sh
test-network-nano-bash/peer1.sh
test-network-nano-bash/peer1admin.sh
test-network-nano-bash/peer2.sh
test-network-nano-bash/peer2admin.sh
test-network-nano-bash/peer3.sh
test-network-nano-bash/peer3admin.sh
test-network-nano-bash/peer4.sh
test-network-nano-bash/peer4admin.sh

The scripts do not require bash so switch to sh and add shellcheck linting

Remove bash dependency from test network nano

---

test-network-nano-bash/README.md
test-network-nano-bash/chaincode-external/connection.json
test-network-nano-bash/chaincode-external/metadata.json

This addresses Issue #504. This extends the test-network-nano-bash
sample to offer an option to run a fabric network without using any
containers at all. The chaincode is running as an external service
directly on the host machine.

Add external chaincode service for Nano Test Network

---

asset-transfer-basic/chaincode-typescript/Dockerfile

Podman isn't as lenient as docker when it comes to the syntax of the
Dockerfile and insists on getting the ARG command properly scoped.
This fixes this error:
...
[2/2] STEP 12/15: EXPOSE $CC_SERVER_PORT
Error: error building at STEP "EXPOSE $CC_SERVER_PORT": EXPOSE requires at least one argument

Fix sample external chaincode Dockerfile

---

asset-transfer-ledger-queries/application-java/src/main/java/application/java/App.java
asset-transfer-ledger-queries/application-javascript/app.js
asset-transfer-ledger-queries/chaincode-go/asset_transfer_ledger_chaincode.go
asset-transfer-ledger-queries/chaincode-javascript/lib/asset_transfer_ledger_chaincode.js

-Go chaincode - Paginated range query should return the bookmark so that next page can be requested
-Javascript chaincode - Make query return JSON consistent with Go chaincode
-Javascript app was broken at bookmark query due to invalid JSON parsing from inconsistent chaincode responses
-Javascript and Java app had incorrect comments

Fix ledger queries sample

---

test-network/CHAINCODE_AS_A_SERVICE_TUTORIAL.md

This PR fixes the followings to run the tutorial.
- Add an instruction to set PATH to call the `peer` command.
- Correct an option for `deployCCAAS` to debug Chaincode.
Signed-off-by: Yuki Kondo <yuki.kondo.ob@hitachi.com>

fix docs: Chaincode-as-a-service tutorial

---

asset-transfer-basic/chaincode-javascript/lib/assetTransfer.js

Missing an `await` on the asset-transfer-basic javascript chaincode.
This has been fixed in the main branch but needs to be fixed in the
release-2.2 branch

[release-2.2] Missing await in asset-transfer-basic chaincode

---

asset-transfer-basic/rest-api-typescript/README.md
asset-transfer-basic/rest-api-typescript/demo.http
asset-transfer-basic/rest-api-typescript/src/__tests__/api.test.ts
asset-transfer-basic/rest-api-typescript/src/assets.router.ts
asset-transfer-basic/rest-api-typescript/src/server.ts

1. For development purposes CORS can hinder testing examples. Therefore enable CORS if needed, default off
2. The default chaincode use Capitalized JSON Names, whereas for new asset the REST validation didn't.. Adjusted
so it matches the chaincode

Update the REST Example

---

test-network-k8s/network
test-network-k8s/scripts/kind.sh

This patch supports for pulling all images to the local docker cache and loading to KIND.
Also, this adds the missing docker image pulling (couchdb) for Fabric.
Signed-off-by: Tatsuya Sato <tatsuya.sato.so@hitachi.com>

test-network-k8s: Support for Loading images for rest sample to KIND

---

test-network/addOrg3/ccp-generate.sh
test-network/addOrg3/ccp-template.yaml

The connection profile file(yaml) generated for Org3 is having wrong indentation and the Fabric Go SDK fails to parse it. This PR fixes the issue.

fix wrong indentationin in the connection profile  generated for Org 3

---

commercial-paper/organization/digibank/application-java/dependency-reduced-pom.xml
commercial-paper/organization/digibank/application-java/pom.xml
commercial-paper/organization/magnetocorp/application-java/dependency-reduced-pom.xml
commercial-paper/organization/magnetocorp/application-java/pom.xml

This PR updates the release-1.4 commercial paper client applications to pull the gateway jars from Maven central.
This PR supersedes PR #585 (abandoned / closed) 
Signed-off-by: lyd <luoyaodong98@gmail.com>
Co-authored-by: Josh Kneubuhl <jkneubuh@us.ibm.com>

Use maven central for gateway client dependencies

---

asset-transfer-basic/application-gateway-typescript/.npmrc
asset-transfer-events/application-gateway-typescript/.npmrc
asset-transfer-private-data/application-gateway-typescript/.npmrc

Use an .npmrc to enable engine-strict checks so that `npm install` will fail for projects when an incompatible Node version is used, rather than confusing errors about unsupported language features occuring at runtime.
Signed-off-by: Mark S. Lewis <mark_lewis@uk.ibm.com>

Enable engine-strict checks for TypeScript Gateway samples

---

chaincode/marbles02/go/marbles_chaincode.go

Running examples should work off-the-shelf. CouchDB now forces to use user_name & password for authentication. This patch fixes an existing example (marbles_chaincode) to work with the current requirements of CouchDB.
Signed-off-by: Obadah Hammoud <obadah.hammoud@outlook.com>

Update marbles_chaincode.go example

---

test-network-k8s/scripts/chaincode.sh
test-network-k8s/scripts/channel.sh
test-network-k8s/scripts/utils.sh

this fix replace hardcoded port 443 with NGINX_HTTPS_PORT which is useful in case ingress is installed on non conventional ports

fix to replace 443 with NGINX_HTTPS_PORT

---

asset-transfer-secured-agreement/application-javascript/app.js
asset-transfer-secured-agreement/chaincode-go/asset_transfer.go

Included check for the client org id to match the peer org id for functions that requires it.

added last fixes for asset-transfer-secured-agreement

---

test-network-k8s/kube/fabric-builder-role.yaml
test-network-k8s/network

This PR updates the k8s chaincode builder for the sample network to use [v0.6.0](https://github.com/hyperledgendary/fabric-builder-k8s/releases/tag/v0.6.0), including support for couchbase index configuration for chaincode packages with `type=k8s` 

Bump chaincode builder to v0.6.0 : +couchdb indexes

---

asset-transfer-events/chaincode-java/settings.gradle
ci/azure-pipelines.yml

- chaincode-java Gradle project name did not match the instructions or the chaincode name used by the sample application code.
- Added test of Java chaincode to CI pipeline.

Fix asset-transfer-events sample Java chaincode

---

test-network-k8s/config/org0/fabric-ca-server-config.yaml
test-network-k8s/config/org1/fabric-ca-server-config.yaml
test-network-k8s/config/org2/fabric-ca-server-config.yaml
test-network-k8s/kube/fabric-rest-sample.yaml
test-network-k8s/kube/org0/org0-ca.yaml
test-network-k8s/kube/org1/org1-ca.yaml
test-network-k8s/kube/org1/org1-peer1.yaml
test-network-k8s/kube/org1/org1-peer2.yaml
test-network-k8s/kube/org2/org2-ca.yaml
test-network-k8s/kube/org2/org2-cc-template.yaml
test-network-k8s/kube/org2/org2-cc.yaml
test-network-k8s/kube/org2/org2-peer1.yaml
test-network-k8s/kube/org2/org2-peer2.yaml
test-network-k8s/scripts/ccp-template.json

Issues:
1. When the name of NETWORK_NAME or NS in file "network" (i.e., the namespace in k8s) is changed from "test-network", the resources in the k8s cluster cannot be created successfully when the command "./network up" is executed.
Error message: error: the namespace from the provided object "test-network" does not match the namespace "xxxxxx". You must pass '--namespace=test-network' to perform this operation.
2. org2-cc.yaml is not completed.
Fix:
1. Replace "test-network" in yaml files in folder "kube" with "${NS}".
2. Complete "org2-cc-template.yaml" by referring to "org1-cc-template.yaml".

Fix namespace in k8s configuration files

---

asset-transfer-secured-agreement/application-gateway-typescript/src/app.ts
asset-transfer-secured-agreement/application-gateway-typescript/src/contractWrapper.ts
asset-transfer-secured-agreement/application-javascript/app.js
asset-transfer-secured-agreement/chaincode-go/asset_transfer.go
asset-transfer-secured-agreement/chaincode-go/asset_transfer_queries.go

A recent commit added the potential buyer to an asset's state based endorsement policy.
That change was problematic because if the transfer fell through, the buyer lost control of the asset,
in that they could no longer update the asset or change the sell price or sell to somebody else.
The asset state based endorsement policy is now based on the seller only, and we document
that additional parties could be added such as a trusted third party (although no
such party exists in test network at this time).
This commit also re-adds some necessary verifications, and make other minor edits and
comments to help users understand the sample.

Update secured asset transfer sample

---

asset-transfer-basic/chaincode-typescript/npm-shrinkwrap.json
asset-transfer-basic/chaincode-typescript/package.json

npm audit reveals several high and one critical vulnerabilities in the dependencies of asset-transfer-basic/chaincode-typescript:
ansi-regex  4.0.0 - 4.1.0
Severity: high
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/nyc/node_modules/ansi-regex
minimist  <=1.2.5
Severity: critical
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
Prototype Pollution in minimist - https://github.com/advisories/GHSA-vh95-rmgr-6w4m
fix available via `npm audit fix --force`
Will install mocha@10.0.0, which is a breaking change
node_modules/minimist
node_modules/ts-node/node_modules/minimist
mkdirp  0.4.1 - 0.5.1
Depends on vulnerable versions of minimist …

Fix vulnerabilities in typescript chaincode deps

---

test-network/README.md
test-network/scripts/deployCCAAS.sh

This change updates the test-network README with up-to-date information
about using podman on Mac and improves support for podman in deployCCAAS.sh

Update podman support information

---

asset-transfer-basic/chaincode-java/Dockerfile

This changes the base image used to build the chaincode-as-a-service
java container to the alpine version which is sufficient and less
taxing than using the full gradle:jdk11 one.

Use alpine based gradle image to build basic transfer java CC container

---

test-network/README.md

Also reverts to using install-fabric.sh which is preferred over bootstrap.sh.

Clarifies podman instructions for test-network

---

test-network-k8s/network
test-network-k8s/scripts/channel.sh
test-network-k8s/scripts/fabric_CAs.sh
test-network-k8s/scripts/test_network.sh

This PR changes the initial CA bootstrap enrollment to run on the _host_ OS, leaving an MSP folder structure on the local storage.  This greatly simplifies the process of registering additional node, client, and admin users with a local `fabric-ca-client` binary. 

Run RCAADMIN registration on the host OS, not in k8s

---

ci/scripts/run-k8s-test-network-basic.sh
test-network-k8s/README.md
test-network-k8s/docs/APPLICATIONS.md
test-network-k8s/docs/CHANNELS.md
test-network-k8s/docs/KUBERNETES.md
test-network-k8s/kube/org1/org1-install-k8s-builder.yaml
test-network-k8s/kube/org2/org2-install-k8s-builder.yaml
test-network-k8s/network
test-network-k8s/scripts/kind.sh

In this PR: 
- The default k8s chaincode builder is upgraded from version 0.6.0 to 0.7.2 
- The `TEST_NETWORK_LOCAL_REGISTRY_INTERFACE` setting can be used to optionally bind the local docker insecure registry to an arbitrary NIC.  By default the registry is bound to the loopback interface 127.0.0.1 
- Switches from `*.vcap.me` to `*.localho.st` for the local host DNS wildcard domain.  (vcap.me is a remnant of an antiquated VMWare product.  Both domain names will match a wildcard to 127.0.0.1 in public DNS.)

Update k8s CC builder to v7.2; Use *.localho.st loopback domain; Optionally bind docker reg to 0.0.0.0

---

ci/azure-pipelines.yml
test-network-k8s/config/org0/configtx-template.yaml
test-network-k8s/kube/fabric-builder-rolebinding.yaml
test-network-k8s/kube/fabric-rest-sample.yaml
test-network-k8s/kube/org0/org0-ca.yaml
test-network-k8s/kube/org0/org0-job-scrub-fabric-volumes.yaml
test-network-k8s/kube/org0/org0-orderer1.yaml
test-network-k8s/kube/org0/org0-orderer2.yaml
test-network-k8s/kube/org0/org0-orderer3.yaml
test-network-k8s/kube/org1/org1-ca.yaml
test-network-k8s/kube/org1/org1-job-scrub-fabric-volumes.yaml
test-network-k8s/kube/org1/org1-peer1.yaml
test-network-k8s/kube/org1/org1-peer2.yaml
test-network-k8s/kube/org2/org2-ca.yaml
test-network-k8s/kube/org2/org2-job-scrub-fabric-volumes.yaml
test-network-k8s/kube/org2/org2-peer1.yaml
test-network-k8s/kube/org2/org2-peer2.yaml
test-network-k8s/network
test-network-k8s/scripts/ccp-template.json
test-network-k8s/scripts/chaincode.sh
test-network-k8s/scripts/channel.sh
test-network-k8s/scripts/fabric_CAs.sh
test-network-k8s/scripts/fabric_config.sh
test-network-k8s/scripts/rest_sample.sh
test-network-k8s/scripts/test_network.sh
test-network-k8s/scripts/utils.sh

Currently all the organizations are in a single namespace. Changes are done in multiple files to create three namespaces and to separate organizations across namespaces.
- ORG0_NS, ORG1_NS, ORG3_NS are defined in network script
- $NS in the scripts are replaced with corresponding namespace
All till chaincode invoke/query is working. I'm yet to test the api server. kind was used for n/w setup, will test on Rancher also.
fixes https://github.com/hyperledger/fabric-samples/issues/644.
Signed-off-by: Basil K Y <techiebasil@gmail.com>

separate namespace for each organization

---

.gitignore
ci/scripts/shellcheck.sh
test-network-nano-bash/.gitignore
test-network-nano-bash/README.md
test-network-nano-bash/create_channel.sh
test-network-nano-bash/generate_artifacts.sh
test-network-nano-bash/join_channel.sh
test-network-nano-bash/network.sh
test-network-nano-bash/orderer1.sh
test-network-nano-bash/orderer2.sh
test-network-nano-bash/orderer3.sh
test-network-nano-bash/peer1.sh
test-network-nano-bash/peer1admin.sh
test-network-nano-bash/peer2.sh
test-network-nano-bash/peer2admin.sh
test-network-nano-bash/peer3.sh
test-network-nano-bash/peer3admin.sh
test-network-nano-bash/peer4.sh
test-network-nano-bash/peer4admin.sh

Fix minor bugs, and add network.sh script to simplify standing up the network
Note: the updated peerNadmin.sh scripts no longer create or join a channel and now only configure the environment for the relevant peer

Update nano test network

---

.github/workflows/enable-gha.yaml

This PR launches a no-op / hello-world action to enable GitHub Actions on the samples repository.
Until this workflow is triggered (once) on the repo, GHA will refuse to run on PRs targeting main.

Activate GHA on fabric-samples

---

.github/workflows/enable-gha.yaml

This PR reduces the frequency of running "hello-GHA" pipelines to target only mainline PRs. 

Only run GHA on PRs targeting the mainline

---

.github/workflows/test-network-k8s.yaml
ci/azure-pipelines.yml

This PR ports the Kubernetes Test Network tests from Azure to GHA.

Move Kube Test Network tests from Azure -> GHA

---

asset-transfer-basic/application-gateway-go/assetTransfer.go

Error handling example used a transaction invocation with the wrong number of arguments and so did not demonstrate the same error condition as other language samples. The error handling code was also not as comprehensive as it should be.
Also changed the console output throughout to match the content and format of the Node and Java samples.

Fix asset-transfer-basic/application-gateway-go

---

off_chain_data/application-java/app/src/main/java/parser/ParsedTransaction.java
off_chain_data/application-java/app/src/main/java/parser/Transaction.java
off_chain_data/application-typescript/src/blockParser.ts

Parsing out of the creator / signer information to provide direct access to their X.509 certificate supports this end-user StackOverflow question:
https://stackoverflow.com/questions/74718400/get-clients-signature-from-the-hyperledger-fabric-block-and-verify-it

Parse transaction creator to Identity in off_chain_data samples

---

token-erc-1155/chaincode-go/chaincode/contract.go
token-erc-20/chaincode-go/chaincode/token_contract.go
token-erc-721/chaincode-go/chaincode/erc721-contract.go
token-utxo/chaincode-go/chaincode/token_contract.go

Stumbled upon this typo across multiple chaincodes when developing with `fabric-samples`
Signed-off-by: Rubén <20502699+rubcv@users.noreply.github.com>

Fix chaincodes typo

---

test-network/network.sh

This adds a missing reference to $CONTAINER_CLI.

Fix network.sh

---

asset-transfer-private-data/application-gateway-typescript/src/app.ts
asset-transfer-private-data/chaincode-go/chaincode/asset_transfer.go
asset-transfer-private-data/chaincode-go/go.mod
asset-transfer-private-data/chaincode-go/go.sum
asset-transfer-private-data/chaincode-java/build.gradle
asset-transfer-private-data/chaincode-java/src/main/java/org/hyperledger/fabric/samples/privatedata/AssetTransfer.java
ci/scripts/lint-java.sh
interest_rate_swaps/network/configtx.yaml
test-network-nano-bash/configtx.yaml
test-network/configtx/configtx.yaml

- Update the configtx.yaml to enable the 2.5 capabillity
- Added purge into the chancode
- Added pruge into the application client code.

Add in examples and notes on using PurgePrivateData

---

commercial-paper/organization/digibank/contract-java/src/main/java/org/example/CommercialPaperContract.java
commercial-paper/organization/magnetocorp/contract-java/src/main/java/org/example/CommercialPaperContract.java

In Java contract of "commercial paper" example, the "paperkey" is not equivalent of "paperNumber" parameter only, but  it's a combination of "issuer" and "paperNumber" params.
this is already done for Js https://github.com/hyperledger/fabric-samples/blob/main/commercial-paper/organization/magnetocorp/contract/lib/papercontract.js#L104

Fix java contract paperkey parameter in commercial paper example

---

asset-transfer-basic/chaincode-java/Dockerfile

This patch fixes the gradle version used in asset-transfer-basic/chaincode-java build to 7.
The reason is because the gradle version in the gradle:jdk11-alpine image is updated from 7 to 8, which seems to cause the build to fail. The result of running docker build command with gradle:jdk11-alpine are as follows:
```bash
Step 4/16 : RUN gradle --no-daemon build shadowJar -x checkstyleMain -x checkstyleTest
---> Running in d245170e621f
Welcome to Gradle 8.0.1!
Here are the highlights of this release:
- Improvements to the Kotlin DSL
- Fine-grained parallelism from the first build with configuration cache
- Configurable Gradle user home cache cleanup
For more details see https://docs.gradle.org/8.0.1/release-notes.html
To honour the JVM settings for this build a single-use Daemon process …
```

Fix gradle version used in asset-transfer-basic/chaincode-java image

---

hardware-security-module/README.md
hardware-security-module/application-go/hsm-sample.go
hardware-security-module/application-typescript/src/hsm-sample.ts
hardware-security-module/scripts/generate-hsm-user.sh

Also:
- Tidy up README documentation.
- Add MacOS/Homebrew (Apple silicon) default SoftHSM library location to HSM scripts and sample applications to avoid the need to explicitly override the library location when running the sample.

Fix Node HSM sample

---

hardware-security-module/scripts/generate-hsm-user.sh
test-network/addOrg3/fabric-ca/registerEnroll.sh
test-network/organizations/fabric-ca/registerEnroll.sh

Flag --csr.hosts is only relevant for tls enrollments, it adds the SAN to the TLS cert.
For msp enrollments, the cert is only used for identity, therefore there is no need for SAN and no need to pass --csr.hosts. 
Having --csr.hosts for msp enrollments is misleading, this commit removes it.

Remove csr.hosts from msp enrollments

---

asset-transfer-private-data/chaincode-go/collections_config.json
asset-transfer-private-data/chaincode-java/collections_config.json
ci/scripts/run-test-network-private.sh

For the asset transfer example (https://hyperledger-fabric.readthedocs.io/en/release-2.5/private_data_tutorial.html#pd-use-case)  there are three private data collections, one per org and one shared between the orgs.
The shared collection didn't have an endorsement policy so inherited the chaincodes; this was specifically set away from the default to be OR(Org1MSP,Org2MSP).   The documentation says this is to ensure that either organization can create an asset. Whilst this is strictly correct, it is misleading - it doesn't need to be a chaincode wide policy, but specifically to the shared collection. 
Therefore it is better to leave the chaincode policy at its default and move the specific policy down to the collection. 
With the context of this example as coded, this is exactly …

AssetTransfer Private - Incorrect Endorsement Policy

---

.github/actions/fsat-setup/action.yaml
.github/actions/test-network-setup/action.yaml
.github/workflows/lint.yaml
.github/workflows/rest-sample.yaml
full-stack-asset-transfer-guide/applications/trader-typescript/package.json
full-stack-asset-transfer-guide/applications/trader-typescript/tsconfig.json
full-stack-asset-transfer-guide/contracts/asset-transfer-typescript/Dockerfile
full-stack-asset-transfer-guide/contracts/asset-transfer-typescript/package.json
full-stack-asset-transfer-guide/contracts/asset-transfer-typescript/tsconfig.json
full-stack-asset-transfer-guide/tests/10-appdev-e2e.sh

A typo in the 10-appdev-e2e.sh script caused the shell to exit with an error status, failing the build.
Also:
- Update sample application and smart contract to Node 18, using the latest fabric-contact-api release.
- Use release versions of Fabric v2.5 and update tool versions in workflow set up.
- Use GitHub Action to install just instead of curl of install script.

Fix build failure in full-stack-asset-transfer

---

test-network/addOrg3/fabric-ca/org3/fabric-ca-server-config.yaml

The org3 affiliation is needed when registering users for org3.
Resolves https://github.com/hyperledger/fabric/issues/4155

Add test-network org3 affiliation

---

test-network-k8s/network

This PR updates test-network-k8s to use Fabric v2.5.
This PR enhances the following PR.
https://github.com/hyperledger/fabric-samples/pull/1033
- https://github.com/hyperledger-labs/fabric-builder-k8s/pull/92
- https://github.com/hyperledger/fabric-samples/issues/840

Update test-network-k8s to Fabric v2.5

---

MAINTAINERS.md

Tatsuya has been helping to groom fabric-samples for multiple years. More recently, Tatsuya has helped to keep test-network-k8s and full-stack-asset-transfer samples working well. Tatsuya has expressed interest in becoming a maintainer and I would welcome the addition!

Nominate Tatsuya Sato as fabric-samples maintainer

---

token-erc-20/chaincode-go/chaincode/token_contract.go

The general overflow  judgment condition for function add is not in every case.
for example, b = 5, q = -3, sum = 2, 
if (sum < q) == (b >= 0 && q >= 0) wil be true.
I modify this line for making it satisfied with every case.

Update token_contract.go, modify the overflow judgment condition for function add().

---

full-stack-asset-transfer-guide/infrastructure/kind_with_nginx.sh

This patch extends the sleep time to wait for starting nginx by following the description on [full-stack-asset-transfer-guide/justfile](https://github.com/hyperledger/fabric-samples/blob/ae9e7e8df8e2932e235a89b79c31dc54c47a3cf6/full-stack-asset-transfer-guide/justfile#L79) to stabilize the intergration test.

FSAT: Extend sleep time to stabilize integration test

---

test-network/network.sh

Hi there,
I noticed that when shutting down a test network using `./network.sh down`, the `networkDown()` function will kill the chaincode-as-a-service containers by querying for all containers with name `ccaas`. However, if you did not deploy your chaincode as a service, this `docker kill` command will give an ugly error message as the following:
```
Removing remaining containers
Removing generated chaincode docker images
"docker kill" requires at least 1 argument.
See 'docker kill --help'.
Usage:  docker kill [OPTIONS] CONTAINER [CONTAINER...]
Kill one or more running containers
```
Also, I believe this command is a bit misplaced as it is more logical to have it in `clearContainers()` function. Therefore, I moved the line to the latter function and discarded its stderr (aligned with …

fix(test-network): ignore the error output when killing CCAAS containers

---

test-network/README.md
test-network/bft-config/configtx.yaml
test-network/compose/compose-bft-test-net.yaml
test-network/compose/compose-test-net.yaml
test-network/compose/docker/docker-compose-bft-test-net.yaml
test-network/network.sh
test-network/organizations/cryptogen/crypto-config-orderer.yaml
test-network/scripts/add_new_orderer_to_config.py
test-network/scripts/createChannel.sh
test-network/scripts/envVar.sh
test-network/scripts/orderer.sh
test-network/scripts/orderer2.sh
test-network/scripts/orderer3.sh
test-network/scripts/orderer4.sh

Added a new option for creating channel:
Running ./network.sh createChannel -bft will initiate a channel running BFT orderers.

Fix test-network to work with BFT consensus.

---

test-network/README.md
test-network/network.sh
test-network/scripts/createChannel.sh
test-network/scripts/utils.sh

This patch includes:
- Fixed a minor bug in the parsing of the BFT flag
- Update of printHelp for use of the BFT flag
- Fixed explanations

Improve BFT sample on test-network

---

test-network/bft-config/configtx.yaml

This patch fixes the description of orderer2-4 in OrdererEndpoints in test-network's bft-config/configtx.yaml.
I noticed that the current configuration in the configtx.yaml file lists all endpoints under "orderer.example.com" with different port numbers. I wonder if the orderer names should be distinct, such as 'orderer2.example.com', 'orderer3.example.com', and 'orderer4.example.com', each with their respective port numbers.
I commented out the first entry of orderer.example.com:7050 temporarily to see if peers have trouble pulling blocks from the other endpoints as shown in the following log.
```bash
$ docker logs peer0.org1.example.com
...
2023-08-29 05:12:55.161 UTC 005b WARN [peer.blocksprovider] DeliverBlocks -> Could not connect to ordering service: could not dial endpoint …
```

Fix OrdererEndpoints in test-network's bft sample

---

test-network/network.sh
test-network/organizations/cfssl/admin-csr-template.json
test-network/organizations/cfssl/ca-orderer.json
test-network/organizations/cfssl/ca-peer.json
test-network/organizations/cfssl/cert-signing-config.json
test-network/organizations/cfssl/client-csr-template.json
test-network/organizations/cfssl/orderer-csr-template.json
test-network/organizations/cfssl/peer-csr-template.json
test-network/organizations/cfssl/registerEnroll.sh
test-network/scripts/utils.sh

This PR adds a new example to support pluggable CA in hyperledger fabric. Current examples in the `fabric-samples` provide two implementations for cert generation i.e `cryptogen` and `fabric-ca`. 
This PR will help the developers to understand more about bring your own identity. These changesets will allow developers to generate certificates using the [cfssl tool](https://github.com/cloudflare/cfssl), which is an opensource tool by cloudflare for cert management.
Generate certs using cfssl
```
./network.sh up -cfssl
```

cfssl to generating certificates

---

test-network/scripts/ccutils.sh

Without this, the init command fails if the chaincode container is not ready.

add a retry to the test-network ccaas chaincode init command

---

test-network/network.config
test-network/network.sh
test-network/scripts/ccutils.sh
test-network/scripts/deployCC.sh
test-network/scripts/packageCC.sh
test-network/scripts/utils.sh

This change is meant to help cover end user functionality that was previously covered by the blockchain VSCode Plugin.
Functions added:
- cc mode with package, list chaincode, invoke and query functions
- auto sequencing for chaincode deployment
- move variables into config file

Add chaincode utilities

---

test-network/scripts/deployCCAAS.sh

Resolves a regression introduced in e73bb717db47185a8ccd1b701503b369cd2a73e1.
Previous change defaulted to "auto" as the sequence number but omitted the call to generate the correct sequence number for the "auto" value. This resulted in "auto" being used as the sequence number, which is an error since an integer is required.

Fix test-network chaincode-as-a-service deployment

---

test-network/network.sh

This patch updates comments to reflect channel profile name changes in test-network.
- https://github.com/hyperledger/fabric-samples/issues/1131
- https://github.com/hyperledger/fabric/pull/4528

test-network: Update comments to reflect channel profile name changes

---

test-network/addOrg3/addOrg3.sh
test-network/network.sh
test-network/scripts/createChannel.sh
test-network/scripts/deployCCAAS.sh

Linux servers with docker engine installed through [docker document](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) could not run `network.sh` successfully due to docker compose version compatibility. The default docker engine doesn't support `docker-compose` command.
As the [docker document](https://docs.docker.com/compose/migrate/#what-does-this-mean-for-my-projects-that-use-compose-v1) suggest, `docker compose` is preferred to use in docker compose V2.
This PR adds support for docker compose V2 version. It uses `docker compose` command if it finds `docker-compose` command fails to execute.

add support for docker compose v2 (fix #730)

---

test-network-k8s/scripts/chaincode.sh

for instance:
```bash
APPROVE_EXTRA_ARGS="--init-required" COMMIT_EXTRA_ARGS="--init-required" ./network chaincode deploy mychaincode ../mychaincode
INVOKE_EXTRA_ARGS="--isInit" ./network chaincode invoke mychaincode '{"Args":["init"]}'
```

add extra arguments to lifecycle commands for more flexibility

---

.github/actions/fsat-setup/action.yaml
.github/actions/test-network-setup/action.yaml
.github/workflows/lint.yaml

Avoid using deprecated action versions based on Node versions prior to Node 18.

Update GitHub action versions

---

asset-transfer-basic/chaincode-external/README.md
asset-transfer-basic/chaincode-external/sampleBuilder/bin/build
asset-transfer-basic/chaincode-external/sampleBuilder/bin/detect
asset-transfer-basic/chaincode-external/sampleBuilder/bin/release

- Bug fix
- Documentation update
This PR fixes docs and scripts for asset-transfer-basic as an external service.
The path to the configuration file that the peer container in the test-network references seems to have changed. So we need to update the path in the procedures.
As discussed in the following mailing list exchange, starting with Fabric v2.5, so we need to change the scripts (detect, build, release, run) to start with #!/bin/bash instead of #!/bin/sh.
https://lists.hyperledger.org/g/fabric/topic/104464487
Resolves #1137

Fix docs and scripts for asset-transfer-basic as an external service

---

test-network/scripts/envVar.sh

Change shell script to use single equals.
In my shell environment single bracket with double equals did not work. It caused failure when running the chaincode-external tutorial README.
It looks like for maximum portability, it is best to use single bracket with single equals.

test-network envVar.sh script improvement

---

test-network/.gitignore
test-network/addOrg3/addOrg3.sh
test-network/scripts/configUpdate.sh
test-network/scripts/envVar.sh
test-network/scripts/org3-scripts/joinChannel.sh
test-network/scripts/org3-scripts/updateChannelConfig.sh
test-network/scripts/setAnchorPeer.sh

This patch aims to refactor the test-network in several aspects, the initial PR (#1186) for the decoupling of the fabric-tools image from fabric-samples.
For context, please refer to the discussions on that PR.
- Rename 'test_network_home' env var to 'TEST_NETWORK_HOME'
- Dedicate the intermediate artifacts related to configtx to channel-artifacts
- Refer to core.yaml in fabric-samples/config, similar to org1 and 2, instead of adding a new core file
- Remove unnecessary functions and comments for CLI container
- Other minor modifications
Related Issues:
- https://github.com/hyperledger/fabric-samples/pull/1186

Refactor test-network post-decoupling fabric-tools image

---

test-network/scripts/configUpdate.sh
test-network/scripts/setAnchorPeer.sh

With removal of fabric-tools image, test-network
now depends on jq being installed locally.
This commit logs an error message if jq commands
fail due to jq not being installed locally.

test-network error message if jq not installed

---

.github/actions/fsat-setup/action.yaml
.github/actions/test-network-setup/action.yaml
.github/workflows/lint.yaml
.github/workflows/rest-sample.yaml
.github/workflows/test-fsat.yaml
.github/workflows/test-network-basic.yaml
.github/workflows/test-network-events.yaml
.github/workflows/test-network-gateway.yaml
.github/workflows/test-network-hsm.yaml
.github/workflows/test-network-k8s.yaml
.github/workflows/test-network-ledger.yaml
.github/workflows/test-network-off-chain.yaml
.github/workflows/test-network-private.yaml
.github/workflows/test-network-sbe.yaml
.github/workflows/test-network-secured.yaml

GHA: Use ubuntu-20.04 for local forks
since local forks don't have access to fabric-ubuntu-20.04.

GHA: Use ubuntu-20.04 for local forks

---

full-stack-asset-transfer-guide/justfile

full-stack-asset-transfer points to an old image.
Point to the hyperledger-labs microfab image instead.
Also, pass the orderer endpoint in lifecycle commands
instead of using the channel config fallback.

Switch microfab to hyperledger-labs version

---

asset-transfer-basic/chaincode-java/build.gradle
asset-transfer-basic/chaincode-java/src/test/java/org/hyperledger/fabric/samples/assettransfer/AssetTransferTest.java
asset-transfer-private-data/chaincode-java/build.gradle
asset-transfer-private-data/chaincode-java/src/test/java/org/hyperledger/fabric/samples/privatedata/AssetTransferTest.java
token-erc-20/chaincode-java/build.gradle
token-erc-721/chaincode-java/build.gradle
token-erc-721/chaincode-java/src/test/java/org/hyperledger/fabric/samples/erc721/ERC721TokenContractTest.java

This resolves mocking errors using the latest Java chaincode shim and very old versions of Mockito.

Update test dependencies for Java chaincode

---

.github/actions/test-network-setup/action.yaml
.github/workflows/lint.yaml
full-stack-asset-transfer-guide/infrastructure/sample-network/network
test-network/addOrg3/compose/compose-couch-org3.yaml
test-network/addOrg3/compose/podman/podman-compose-couch-org3.yaml
test-network/compose/compose-couch.yaml
test-network/scripts/utils.sh

Go to 1.22
CouchDB to 3.3.3
Fabric to 2.5.7
Fabric-CA to 1.5.10

Bump dependencies

---

README.md
asset-transfer-basic/chaincode-javascript/npm-shrinkwrap.json
asset-transfer-basic/chaincode-javascript/package.json
asset-transfer-basic/chaincode-typescript/npm-shrinkwrap.json
asset-transfer-basic/chaincode-typescript/package.json
asset-transfer-events/chaincode-javascript/npm-shrinkwrap.json
asset-transfer-events/chaincode-javascript/package.json
asset-transfer-ledger-queries/chaincode-javascript/npm-shrinkwrap.json
asset-transfer-ledger-queries/chaincode-javascript/package.json
asset-transfer-private-data/chaincode-typescript/npm-shrinkwrap.json
asset-transfer-private-data/chaincode-typescript/package.json
asset-transfer-sbe/chaincode-typescript/npm-shrinkwrap.json
asset-transfer-sbe/chaincode-typescript/package.json
full-stack-asset-transfer-guide/contracts/asset-transfer-typescript/package.json
token-erc-20/chaincode-javascript/npm-shrinkwrap.json
token-erc-20/chaincode-javascript/package.json
token-erc-721/chaincode-javascript/npm-shrinkwrap.json
token-erc-721/chaincode-javascript/package.json

This demonstrates good practice in restricting the chaincode package versions to those applicable for the specific Fabric (major/minor) version targeted for deployment.
Also some corrections to the repository README. Particularly referring to other branches for samples targeted at earlier Fabric versions, since samples in the main branch may exploit features not available in older Fabric releases, which can cause confusion for end users.

Use more specific chaincode package versions

---

asset-transfer-basic/chaincode-javascript/package.json
asset-transfer-basic/chaincode-typescript/package.json
asset-transfer-events/chaincode-javascript/package.json
asset-transfer-ledger-queries/chaincode-javascript/package.json
asset-transfer-sbe/chaincode-typescript/package.json
chaincode/abstore/javascript/package.json
chaincode/fabcar/javascript/package.json
chaincode/fabcar/typescript/package.json
chaincode/marbles02/javascript/package.json
commercial-paper/organization/digibank/contract/package.json
commercial-paper/organization/magnetocorp/contract/package.json
token-erc-20/chaincode-javascript/package.json

Avoid chaincode packages picking up dependencies on later v2.x releases, such as v2.5.x. Later releases may exploit features not compatible with the v2.2 chaincode container runtime.

Use only v2.2.x chaincode package dependencies (release-2.2)

---

.github/actions/test-network-setup/action.yaml
full-stack-asset-transfer-guide/infrastructure/sample-network/network
test-network/scripts/utils.sh

Bump fabric to v2.5.9

---

.editorconfig
asset-transfer-basic/README.md
asset-transfer-basic/application-gateway-javascript/.gitignore
asset-transfer-basic/application-gateway-javascript/.npmrc
asset-transfer-basic/application-gateway-javascript/eslint.config.mjs
asset-transfer-basic/application-gateway-javascript/package.json
asset-transfer-basic/application-gateway-javascript/src/app.js
ci/scripts/run-test-network-basic.sh

While the TypeScript application sample is essentially identical (with the addition of some type declarations), there seems to be sufficient uncertainty amongst JavaScript developers not familiar with TypeScript on how best to implement a JavaScript application that it is worthwhile having one plain JavaScript sample using the current client API.

Add JavaScript asset-transfer-basic application

---

test-network/network.config
test-network/scripts/packageCC.sh

This patch fixes the default chaincode version to "1.0" in test-network.
See [this discussion](https://github.com/hyperledger/fabric/pull/4770).

Fix the default chaincode version to "1.0" in test-network

---

test-network-k8s/scripts/prereqs.sh
test-network/network.sh

It seems that PR #1205 has stalled, so I have created a new PR that builds upon the considerations from that one while addressing the issues raised. 
This PR resolves issue #1204 and also addresses the concerns mentioned in PR #1205. Specifically, it:
- Uses the newer install script instead of bootstrap.sh.
- Downloads binaries corresponding to the image versions, supporting both two-digit and three-digit Fabric version specifications.
Related issue:
Resolves #1204

test-network-k8s: Improve prereqs logic

---

.github/workflows/lint.yaml
.github/workflows/rest-sample.yaml
.github/workflows/test-fsat.yaml
.github/workflows/test-network-basic.yaml
.github/workflows/test-network-events.yaml
.github/workflows/test-network-hsm.yaml
.github/workflows/test-network-k8s.yaml
.github/workflows/test-network-ledger.yaml
.github/workflows/test-network-off-chain.yaml
.github/workflows/test-network-private.yaml
.github/workflows/test-network-sbe.yaml
.github/workflows/test-network-secured.yaml
test-network-nano-bash/orderer1.sh
test-network-nano-bash/orderer2.sh
test-network-nano-bash/orderer3.sh
test-network-nano-bash/orderer4.sh

Since Fabric v3.0 builds on ubuntu 22.04,
it will be necessary for samples CI to run on ubuntu 22.04.
Both Fabric v2.5 components (ubuntu 20.04) and
Fabric v3.0 components (ubuntu 22.04) work on
ubuntu 22.04 runtime.
The update also requires shell script updates to pass linting.

Bump ubuntu to 22.04 in CI

---

test-network/compose/podman/podman-compose-test-net.yaml

I removed the `cli` entry from the `podman-compose-test-net.yaml` file.
This PR closes #1258.

Remove cli from podman compose file

---

test-network/addOrg3/compose/docker/peercfg/core.yaml
test-network/addOrg3/compose/podman/peercfg/core.yaml
test-network/compose/docker/peercfg/core.yaml
test-network/compose/podman/peercfg/core.yaml

The test-network peer configuration specifies $(TWO_DIGIT_VERSION) as the tag for the Node and Java chaincode containers. For Fabric v3.0, this requests fabric-nodeenv:3.0 and fabric-javaenv:3.0 Docker images to host Node and Java chaincode respectively. These images do not exist, which causes deployment of Node and Java chaincode to fail when using Fabric v3.0. Fabric v3.0 continues to use fabric-nodeenv:2.5 and fabric-javaenv:2.5.
This change updates the test-network peer configuration to explicitly specify `2.5` as the Node and Java chaincode Docker image tags. This is (currently) the correct version for both Fabric v2.5 and Fabric v3.0.
Closes #1267

Update test-network chaincode container versions

---

full-stack-asset-transfer-guide/infrastructure/sample-network/config/core.yaml
test-network-k8s/config/org1/core.yaml
test-network-k8s/config/org2/core.yaml

This patch updates chaincode container versions to 2.5 in the following samples:
- test-network-k8s
- full-stack-asset-transfer-guide
- https://github.com/hyperledger/fabric-samples/issues/1267
- https://github.com/hyperledger/fabric-samples/pull/1266

Update chaincode container versions in k8s samples

---

full-stack-asset-transfer-guide/justfile
full-stack-asset-transfer-guide/tests/10-appdev-e2e.sh

The new microfab release seems to start slower than the previous release. This might be due to a change from solo to raft consensus. This causes failures in the full-stack-asset-transfer appdev tests. Chaincode deployment fails since the channel is not yet available.
Instead of increasing the sleep time after launching microfab, this change attempts to wait however long is required by looking for the "Microfab started" message in the container log before proceeding.
The test script is also updated to correctly stop the external chaincode process when the script exits. Previously the process ID of the npm command used to lauch the chaincode was captured rather than the actual chaincode process.

Fix build with new microfab release

---

full-stack-asset-transfer-guide/docs/SmartContractDev/01-Exercise-Getting-Started-ES.md
full-stack-asset-transfer-guide/docs/SmartContractDev/01-Exercise-Getting-Started.md

A behaviour change in microfab means that the orderer endpoint needs to be explicitly specified when using the peer CLI to submit transactions. Ideally the microfab environment would not require this but the documented commands do not currently work without this.
This change updates the full-stack-asset-transfer-guide documentation so that CLI commands include the orderer endpoint explicitly.

Fix invoke CLI commands in full-stack guide

---

asset-transfer-private-data/chaincode-go/chaincode/asset_transfer.go
asset-transfer-private-data/chaincode-java/src/main/java/org/hyperledger/fabric/samples/privatedata/AssetTransfer.java
asset-transfer-private-data/chaincode-typescript/src/assetTransfer.ts
auction-dutch/chaincode-go-auditor/smart-contract/auction.go
auction-dutch/chaincode-go-auditor/smart-contract/auctionQueries.go
auction-dutch/chaincode-go/smart-contract/auction.go
auction-dutch/chaincode-go/smart-contract/auctionQueries.go
test-network/CHAINCODE_AS_A_SERVICE_TUTORIAL.md
token-erc-20/README.md
token-erc-20/chaincode-go/chaincode/token_contract.go
token-erc-721/README.md
token-erc-721/chaincode-java/src/main/java/org/hyperledger/fabric/samples/erc721/ERC721TokenContract.java
token-utxo/README.md

1. remove repetitive words
2. use errors.New to replace fmt.Errorf with no parameters

chore: use errors.New to replace fmt.Errorf with no parameters

---

test-network-k8s/scripts/prereqs.sh

The kubernetes network does not start correctly on Mac due to a different interpretation of the regex by sed.
```bash
./test-network-k8s/network 
Fabric image versions: Peer (), CA ()
It seems some of the specified Fabric images are not available.
```
Examples for testing the fix:
```bash
docker run --rm hyperledger/fabric-peer:2.5 peer version | sed -ne 's/^ Version: v\?\(.*\)$/\1/p'
docker run --rm hyperledger/fabric-peer:2.5 bash -c "peer version | sed -ne 's/^ Version: v\{0,1\}\(.*\)$/\1/p'"
2.5.9
docker run --rm hyperledger/fabric-peer:2.5 peer version | sed -ne 's/^ Version: v\{0,1\}\(.*\)$/\1/p'
2.5.9
docker run --rm hyperledger/fabric-peer:2.5 bash -c "echo ' Version: 2.5.9' | sed -ne 's/^ Version: v\{0,1\}\(.*\)$/\1/p'"
2.5.9
```

make version regex posix compliant so that it works on mac

---

test-network-k8s/config/org0/bft/configtx-template.yaml
test-network-k8s/kube/org0/org0-orderer4.yaml
test-network-k8s/network
test-network-k8s/scripts/channel.sh
test-network-k8s/scripts/test_network.sh

This PR adds initial support for BFT orderers in the test-network-k8s.
When `TEST_NETWORK_ORDERER_TYPE` is set to `bft`, the network launches four orderers configured with SmartBFT.
I plan to update the documentation after this PR is merged.
```bash
cd test-network-k8s
export TEST_NETWORK_FABRIC_VERSION=3.0
export TEST_NETWORK_ORDERER_TYPE=bft
./network kind
./network cluster init
./network up
./network channel create
./network chaincode deploy asset-transfer-basic ../asset-transfer-basic/chaincode-java
./network chaincode invoke asset-transfer-basic '{"Args":["InitLedger"]}'
./network chaincode query  asset-transfer-basic '{"Args":["ReadAsset","asset1"]}'
```

test-network-k8s: Introduce initial support for BFT orderers

---

.github/workflows/test-network-bft-orderer.yaml
.github/workflows/test-network-k8s.yaml
ci/scripts/run-k8s-test-network-basic.sh
ci/scripts/run-test-network-basic.sh

This patch adds BFT Orderer testing to the CI workflows. The following test environments are updated:
- test-network
- test-network-k8s
Currently, the fabric-samples CI is primarily focused on the latest LTS version, Fabric v2.5.x. However, BFT Orderer support is available only in Fabric v3.0 or later.
To address this, the BFT Orderer tests explicitly specify Fabric v3.0, while other tests continue to use the default version (v2.5.x).
I believe this approach ensures that both the latest LTS version (v2.5) and v3.0 tests are supported with minimal changes.
- https://github.com/hyperledger/fabric-samples/pull/1294

CI: Add BFT Orderer support

---

test-network-k8s/README.md
test-network-k8s/docs/BFT_ORDERERS.md
test-network-k8s/docs/README.md

This patch adds documentation for initial BFT orderer support.
- https://github.com/hyperledger/fabric-samples/pull/1294

test-network-k8s: Add documentation for initial BFT orderer support

---

test-network-nano-bash/ordererca.sh
test-network-nano-bash/org1ca.sh
test-network-nano-bash/org2ca.sh

test-network-nano-bash is often used with locally built fabric and fabric-ca binaries.
As such the intent is to first look for locally
built binaries and then fall back to binaries downloaded with the samples.
This was correct for fabric binaries but not the fabric-ca binaries.

Update CA server bin path in test-network-nano-bash

---

.github/workflows/test-network-bft-orderer.yaml
ci/scripts/run-test-network-basic.sh
test-network/.gitignore
test-network/README.md
test-network/network.sh
test-network/organizations/fabric-ca/registerEnroll.sh
test-network/scripts/createChannel.sh

test-network: Add support for using BFT consensus with CA

---

test-network-nano-bash/ca/ca_utils.sh
test-network-nano-bash/ca/createEnrollments.sh
test-network-nano-bash/generate_artifacts.sh

Fix test-network-nano-bash orderer4 enrollment.
Also improve error handling and messages in CA interaction.

Fix test-network-nano-bash orderer4 enrollment

---

test-network-nano-bash/ca/ccp-generate.sh
test-network-nano-bash/ca/ccp-template.json
test-network-nano-bash/ca/ccp-template.yaml
test-network-nano-bash/ca/createEnrollments.sh

Add connection profile to test-network-nano-bash
to enable legacy SDK apps.
Approach copied from test-network connection profiles.

Add connection profile to test-network-nano-bash

---

test-network/network.sh

If CA server hasn't finished initialization then the initial register and enroll requests will fail.
Waiting 3 seconds resolves the issue.

Fix intermittent errors with test-network ca

---

.github/actions/fsat-setup/action.yaml
.github/actions/test-network-setup/action.yaml

By default, Docker images are referenced from Docker Hub. This has now applied rate limiting that is causing builds to fail. Current Fabric v2.5 and chaincode container Docker images are also published to GitHub Container Registry, which does not impose rate limits and will be located closer to the GitHub Actions runners.
This change:
- Updates to latest Fabric component versions, which are available in GHCR. The Fabric install script defaults to GHCR as the Docker registry for versions that are available here.
- Pulls and re-tags chaincode container images from GHCR in advance of running tests in the build. This avoids them being pulled from Docker Hub during test execution.

Pull Fabric images from GitHub Container Registry

---

.github/actions/fsat-setup/action.yaml
.github/actions/test-network-setup/action.yaml
full-stack-asset-transfer-guide/infrastructure/sample-network/network
test-network/network.config
test-network/scripts/utils.sh

This patch bumps fabric to v2.5.12.
It also updates some parts of fabric-ca that were missed in the previous update.

Bump fabric to v2.5.12

---

.github/workflows/test-network-ledger.yaml
asset-transfer-ledger-queries/chaincode-typescript/.gitignore
asset-transfer-ledger-queries/chaincode-typescript/META-INF/statedb/couchdb/indexes/indexOwner.json
asset-transfer-ledger-queries/chaincode-typescript/eslint.config.mjs
asset-transfer-ledger-queries/chaincode-typescript/npm-shrinkwrap.json
asset-transfer-ledger-queries/chaincode-typescript/package.json
asset-transfer-ledger-queries/chaincode-typescript/src/asset.ts
asset-transfer-ledger-queries/chaincode-typescript/src/assetTransferLedger.ts
asset-transfer-ledger-queries/chaincode-typescript/src/index.ts
asset-transfer-ledger-queries/chaincode-typescript/tsconfig.json

This commit implements the TypeScript version of the asset-transfer-ledger-queries Chaincode.
Resolves #1232

Implement TypeScript version of asset-transfer-ledger-queries

---

test-network-nano-bash/network.sh

Use the operations service health check to detect when nodes are started in test-network-nano-bash instead of using arbitrary sleeps. Depending on the host machine and whether CAs are used, this can reduce network start time by up to 15 seconds.
Also ensure the Docker socket location is set correctly for Docker contexts that use a non-default location. This is required to prevent the health service from returning Docker connection errors.

Detect node start using healthz

---

full-stack-asset-transfer-guide/docs/CloudReady/21-fabric-operations-console.md
full-stack-asset-transfer-guide/infrastructure/sample-network/config/console/hlf-operations-console.yaml

Update docs for Mac users when deploying fabric operations console on local machines.

update fabric operations console docs

---

test-network-nano-bash/ca/ca_utils.sh

Make the CA script logging more readable for users trying to understand the fabric-ca-client commands.
Print the actual command to the log and remove the debug logging which adds noise.

Improve logging for test-network-nano-bash CA

---

off_chain_data/application-go/parser/block.go
off_chain_data/application-go/parser/namespaceReadWriteSet.go
off_chain_data/application-go/parser/payload.go
off_chain_data/application-go/parser/transaction.go

Add some methods to the parsing API within the Go off_chain_data sample for consistency with the Node and Java implementations:
- ToProto() on Block, Transaction and NamespaceReadWriteSet.
- ValidationCode() on Transaction.
- Creator() on Transaction
Addresses [review comments](https://github.com/hyperledger/fabric-samples/pull/1269#pullrequestreview-2661860821) from the initial contribution.

Enhance Go off_chain_data for consistency

---

ci/scripts/run-test-network-ledger.sh

The CI script invoked Gradle directly, which could picker newer Gradle versions not compatible with the build definition. This change uses the Gradle wrapper included in the client application sample.

Use Gradle wrapper in asset-transfer-ledger-queries
