.github/stale.yml

Signed-off-by: Brett Logan <Brett.T.Logan@ibm.com>

Change stalebot settings

---

.github/stale.yml

Signed-off-by: Brett Logan <Brett.T.Logan@ibm.com>

Cherrypick stalebot settings from master

---

basic-network/docker-compose.yml
chaincode-docker-devmode/docker-compose-simple.yaml
first-network/base/peer-base.yaml
interest_rate_swaps/network/docker-compose.yaml

It includes two config changes in fabric recently:
* GenesisMethod --> BootstrapMethod
* GenesisFile --> BootstrapFile
Signed-off-by: Baohua Yang <yangbaohua@gmail.com>
Signed-off-by: Baohua Yang <baohua.yang@oracle.com>

[FAB-17121] Use new bootstrap config in orderer

---

first-network/byfn.sh

Correct chaincode name regexp in byfn.sh so it is not restricted
to one named chaincode.

[FAB-16844] Correct BYFN CC name

---

chaincode/abstore/java/build.gradle
chaincode/abstore/javascript/package.json
chaincode/fabcar/java/build.gradle
chaincode/fabcar/javascript/package.json
chaincode/fabcar/typescript/package.json
chaincode/marbles02/javascript/package.json
commercial-paper/organization/digibank/application-java/pom.xml
commercial-paper/organization/digibank/application/package.json
commercial-paper/organization/digibank/contract/package.json
commercial-paper/organization/magnetocorp/application/package.json
commercial-paper/organization/magnetocorp/contract/package.json
fabcar/javascript/package.json
fabcar/typescript/package.json
off_chain_data/package.json

Update to use beta levels of modules

---

commercial-paper/organization/magnetocorp/contract-java/src/main/java/org/example/ledgerapi/State.java

Originally submitted as PR81 by https://github.com/ArkiZh

Fixed typo

---

MAINTAINERS.md

This change removes the Gerrit reference only

Remove Gerrit reference

---

ci/azure-pipelines.yml
ci/install-deps.yml

Add Support for Versioning NodeJS

---

ci/getDockerImages.sh

Update docker image version

---

first-network/byfn.sh

echo Generating channel configuration transaction 'channel.tx'
it will be output to the console "configtxgen -profile TwoOrgsChannel -outputCreateChannelTx ./channel-artifacts/channel.tx -channelID mychannel"
Signed-off-by: KIM GEONWOO <kgw8919@gmail.com>

[FAB-17656] echo Generating channel.tx

---

.gitignore
ci/azure-pipelines.yml
ci/install-fabric.yml

Fix Fabric Binary Pull Logic

---

commercial-paper/README.md

Fixes several errors, typos, and clarifies some of the instructions.

Fix commercial-paper README

---

fabcar/javascript/package-lock.json
fabcar/javascript/package.json

Signed-off-by: heatherlp <heatherpollard0@gmail.com>

FABN-1531 Use v2.1.0 sdk-node modules

---

fabcar/java/pom.xml

Fix Fabcar java dependencies

---

commercial-paper/organization/digibank/application-java/pom.xml
commercial-paper/organization/magnetocorp/application-java/pom.xml

Signed-off-by: heatherlp <heatherpollard0@gmail.com>

FGJ-81 Update Commerical Paper to use latest v2.1.0 of gateway-java

---

chaincode/fabcar/go/go.sum

add miss checksum

---

test-network/scripts/createChannel.sh

Clarify config tx generation messages.
FAB-17820

Update user echo text in test network

---

test-network/scripts/deployCC.sh

- Bug fix
This patch fixes some wrong messages in test-network
- https://jira.hyperledger.org/browse/FAB-17847

[FAB-17847] Fix some wrong messages in test-network

---

test-network/network.sh

Signed-off-by: duanmeng <duanmeng@cmss.chinamobile.com>

Add CA version argument, CA version does not match fabric version, so it must use another argument

---

first-network/byfn.sh

Signed-off-by: zhuzeyu <zhuzeyu0409@gmail.com>

fix first network byfn.sh usage

---

chaincode/fabcar/javascript/index.js
chaincode/fabcar/javascript/lib/fabcar.js
commercial-paper/organization/digibank/application/addToWallet.js
commercial-paper/organization/digibank/application/buy.js
commercial-paper/organization/digibank/application/enrollUser.js
commercial-paper/organization/digibank/application/redeem.js
commercial-paper/organization/digibank/contract/index.js
commercial-paper/organization/digibank/contract/ledger-api/state.js
commercial-paper/organization/digibank/contract/ledger-api/statelist.js
commercial-paper/organization/digibank/contract/lib/paper.js
commercial-paper/organization/digibank/contract/lib/papercontract.js
commercial-paper/organization/digibank/contract/lib/paperlist.js
commercial-paper/organization/digibank/contract/test/contract.js
commercial-paper/organization/magnetocorp/application/addToWallet.js
commercial-paper/organization/magnetocorp/application/enrollUser.js
commercial-paper/organization/magnetocorp/application/issue.js
commercial-paper/organization/magnetocorp/contract/index.js
commercial-paper/organization/magnetocorp/contract/ledger-api/state.js
commercial-paper/organization/magnetocorp/contract/ledger-api/statelist.js
commercial-paper/organization/magnetocorp/contract/lib/paper.js
commercial-paper/organization/magnetocorp/contract/lib/papercontract.js
commercial-paper/organization/magnetocorp/contract/lib/paperlist.js
commercial-paper/organization/magnetocorp/contract/test/contract.js
fabcar/javascript/enrollAdmin.js
fabcar/javascript/invoke.js
fabcar/javascript/query.js
fabcar/javascript/registerUser.js
off_chain_data/enrollAdmin.js
off_chain_data/registerUser.js

Add missing Copyright in some files

---

CHANGELOG.md
scripts/changelog.sh

Add CHANGELOG.md with script to update it

---

fabcar/java/pom.xml
fabcar/java/src/main/java/org/example/ClientApp.java
fabcar/java/src/main/java/org/example/EnrollAdmin.java
fabcar/java/src/main/java/org/example/RegisterUser.java

This updates the fabcar java application to work with the fabric
gateway java version 2.1.1.
It also changes pom.xml to produce a jar file that is self contained
for ease of use.

FGJ-84 Update Fabcar Java app to 2.1.1

---

chaincode/marbles02_private/go/marbles_chaincode_private.go

Add function to private data hash to sample private data chaincode

---

chaincode/marbles_transfer/README.md
chaincode/marbles_transfer/marbles_transfer.go
chaincode/marbles_transfer/marbles_transfer_queries.go

- Add marbles proposed sale and bid prices queries
- Add marbles history query
- Add verification of ownership when selling marble
Signed-off-by: Tiffany Harris <tiffany.harris@ibm.com>
Signed-off-by: Dereck Luo <dereckluo@gmail.com>

Implement sale, bid, and history queries

---

fabcar/javascript/query.js

After the evaluation of transaction in fabcar -> javascript -> query.js , the gateway was not disconnected.
Hope it helps.

Disconnected from the gateway in fabcar query.js

---

test-network/addOrg3/addOrg3.sh
test-network/network.sh

To get rid of hard-coded versioning and use the latest version of fabric-ca in test-network, this patch modifies the existence check logic of the fabric-ca-client binary in the same way as peer and orderer.
Also, this patch updates addOrg3.sh to use cai <ca_imagetag> option.
- Bug fix
Currently, test-network mainly uses the previous version (1.4.6) of fabric-ca.
Also, addOrg3.sh in test-network is not using the cai <ca_imagetag> option (This may use non-existent version or a hard-coded 1.4.4 version).
So, this should catch up with the latest version (latest or 1.4.7).
- https://jira.hyperledger.org/browse/FAB-17952

[FAB-17952] Fix test-network to use the latest version of fabric-ca

---

chaincode/fabcar/external/fabcar.go
chaincode/fabcar/go/fabcar.go
chaincode/fabcar/java/src/main/java/org/hyperledger/fabric/samples/fabcar/FabCar.java
chaincode/fabcar/java/src/test/java/org/hyperledger/fabric/samples/fabcar/FabCarTest.java
chaincode/fabcar/javascript/lib/fabcar.js
chaincode/fabcar/typescript/src/fabcar.ts

optimize query conditions in fabcar chaincode
Signed-off-by: zhuzeyu <zhuzeyu0409@gmail.com>

Optimize query conditions in fabcar chaincode

---

asset-transfer-basic/chaincode-javascript/.eslintignore
asset-transfer-basic/chaincode-javascript/.eslintrc.js
asset-transfer-basic/chaincode-javascript/.gitignore
asset-transfer-basic/chaincode-javascript/index.js
asset-transfer-basic/chaincode-javascript/lib/assetTransfer.js
asset-transfer-basic/chaincode-javascript/package.json

* Adding javascript chaincode to `asset-transfer-basic` sample.

Adding chaincode-js to asset-transfer-basic sample.

---

asset-transfer-basic/chaincode-typescript/.gitignore
asset-transfer-basic/chaincode-typescript/package.json
asset-transfer-basic/chaincode-typescript/src/asset.ts
asset-transfer-basic/chaincode-typescript/src/assetTransfer.ts
asset-transfer-basic/chaincode-typescript/src/index.ts
asset-transfer-basic/chaincode-typescript/tsconfig.json
asset-transfer-basic/chaincode-typescript/tslint.json

* Adding typescript chaincode to `asset-transfer-basic` sample.

Adding chaincode-typescript to asset-transfer-basic sample.

---

asset-transfer-basic/.gitignore
asset-transfer-basic/application-javascript/.eslintignore
asset-transfer-basic/application-javascript/.eslintrc.js
asset-transfer-basic/application-javascript/.gitignore
asset-transfer-basic/application-javascript/enrollAdmin.js
asset-transfer-basic/application-javascript/invoke.js
asset-transfer-basic/application-javascript/package.json
asset-transfer-basic/application-javascript/query.js
asset-transfer-basic/application-javascript/registerUser.js

* Adding NodeJS application for `asset-transfer-basic` sample.

Adding NodeJS app for asset-transfer-basic sample.

---

chaincode/fabcar/java/src/main/java/org/hyperledger/fabric/samples/fabcar/CarQueryResult.java
chaincode/fabcar/java/src/main/java/org/hyperledger/fabric/samples/fabcar/FabCar.java
chaincode/fabcar/java/src/test/java/org/hyperledger/fabric/samples/fabcar/CarQueryResultTest.java
chaincode/fabcar/java/src/test/java/org/hyperledger/fabric/samples/fabcar/FabCarTest.java

Fix fabcar Java chaincode test & coverage failures

---

asset-transfer-basic/application-javascript/invoke.js

* Adding filepath check for invoke application in order to keep consistent with rest of sample.

Add filepath check for invoke

---

asset-transfer-basic/application-typescript/.gitignore
asset-transfer-basic/application-typescript/package.json
asset-transfer-basic/application-typescript/src/enrollAdmin.ts
asset-transfer-basic/application-typescript/src/invoke.ts
asset-transfer-basic/application-typescript/src/query.ts
asset-transfer-basic/application-typescript/src/registerUser.ts
asset-transfer-basic/application-typescript/tsconfig.json
asset-transfer-basic/application-typescript/tslint.json

* Adding Typescript application for `asset-transfer-basic` sample.

Add application-typescript to asset-transfer-basic

---

README.md

remove link to BYFN in README

---

fabcar/go/fabcar.go
fabcar/go/runfabcar.sh
fabcar/startFabric.sh

add set host and env  to fabcar run go

run fabcar go 

---

asset-transfer-basic/chaincode-go/chaincode/smartcontract.go
asset-transfer-basic/chaincode-go/chaincode/smartcontract_test.go

Fix param sequence, smart contract and smartcontract_test.

Fix param sequence in smartcontract and smartcontract_test.

---

asset-transfer-basic/application-javascript/invoke.js

Fix param sequence for javascript invoke function.

---

asset-transfer-basic/application-typescript/src/invoke.ts

Fix param sequence for typescript invoke function.

---

asset-transfer-ledger-queries/chaincode-go/asset_transfer_ledger_chaincode.go
asset-transfer-ledger-queries/chaincode-go/go.mod
asset-transfer-ledger-queries/chaincode-go/go.sum

constructQueryResponseFromIterator was returning a QueryResult slice as opposed to an Asset slice.

Fix constructQueryResponseFromIterator

---

asset-transfer-secured-agreement/chaincode-go/asset_transfer_queries.go
asset-transfer-secured-agreement/chaincode-go/go.mod

Signed-off-by: Tiffany Harris <tiffany.harris@ibm.com>

Fix unmarshaling asset in ReadAsset()

---

test-network/addOrg3/addOrg3.sh
test-network/addOrg3/fabric-ca/registerEnroll.sh
test-network/network.sh
test-network/organizations/fabric-ca/registerEnroll.sh
test-network/scripts/createChannel.sh
test-network/scripts/deployCC.sh
test-network/scripts/envVar.sh
test-network/scripts/org3-scripts/step1org3.sh
test-network/scripts/org3-scripts/step2org3.sh

This reverts commit d5ce443bee34c54ac43a8aeabb8a38dc23f744e3.

Revert "WIP (#253)"

---

README.md
asset-transfer-secured-agreement/chaincode-go/README.md

Add asset transfer series documentation to Fabric samples README

---

asset-transfer-private-data/chaincode-go/README.md

Use the new deployCC script to deploy the private data smart contract.

Update private data chaincode to use test network script

---

asset-transfer-private-data/chaincode-go/README.md
test-network/scripts/deployCC.sh

Edits to the readme suggested in #249
Feel free to add any more suggestions.
Quick change to a typo in the deployCC script as well.

private data readme edits

---

asset-transfer-basic/application-javascript/app.js

Fix typo in code comment

---

asset-transfer-ledger-queries/chaincode-javascript/lib/asset_transfer_ledger_chaincode.js

I also capitalized 'Tom' as that is what the asset is initialized to.
Signed-off-by: r2roC <arturo@IBM.com>

I removed some unnecessary comments that I left there by accident.

---

test-network/scripts/deployCC.sh

Signed-off-by: tyanj <653291675@qq.com>

res=$? missing

---

asset-transfer-sbe/README.md
asset-transfer-sbe/chaincode-typescript/.gitignore
asset-transfer-sbe/chaincode-typescript/package.json
asset-transfer-sbe/chaincode-typescript/src/asset.ts
asset-transfer-sbe/chaincode-typescript/src/assetContract.ts
asset-transfer-sbe/chaincode-typescript/src/index.ts
asset-transfer-sbe/chaincode-typescript/tsconfig.json
asset-transfer-sbe/chaincode-typescript/tslint.json

Signed-off-by: Gaurav Giri <girigaurav@gmail.com>

fabric samples for state-based endorsement for chaincode typescript

---

README.md

Promote asset transfer as the primary set of samples.
Misc other updates to the README.

Updates to samples README

---

asset-transfer-ledger-queries/chaincode-go/asset_transfer_ledger_chaincode.go

Fix history query results.
Fix paginated query results.

Fix ledger queries sample - history and pagination

---

test-network/network.sh
test-network/scripts/deployCC.sh

We have already added sbe to the deploy CC script. This pr adds it to the help text and error message.

Add sbe to help text

---

asset-transfer-ledger-queries/application-javascript/package.json

Update the package.json to indicate the correct sample
Signed-off-by: Bret Harrison <beharrison@nc.rr.com>

FIx ledger queries package.json

---

asset-transfer-basic/chaincode-external/README.md

Minor clarifications to external chaincode readme.

Update asset-transfer-basic external chaincode readme

---

asset-transfer-basic/application-go/assetTransfer.go
asset-transfer-ledger-queries/chaincode-javascript/.eslintignore
asset-transfer-ledger-queries/chaincode-javascript/.eslintrc.js
asset-transfer-ledger-queries/chaincode-javascript/lib/asset_transfer_ledger_chaincode.js
asset-transfer-sbe/chaincode-typescript/src/asset.ts
asset-transfer-sbe/chaincode-typescript/src/assetContract.ts
ci/azure-pipelines.yml
ci/scripts/run-test-network-basic.sh
ci/scripts/run-test-network-ledger.sh
ci/scripts/run-test-network-sbe.sh
ci/scripts/run-test-network-secured.sh

Add missing apps and chaincodes to CI

---

asset-transfer-basic/application-go/assetTransfer.go

- Bug fix
* added additional logs to application.
* minor fixes

Fix minor issues related to asset-transfer-basic application-go

---

asset-transfer-basic/application-go/assetTransfer.go

- An error occured in asset-transfer-basic/application-go
```
2020/08/27 10:42:15 --> Submit Transaction: CreateAsset, creates new asset with ID, color, owner, size, and appraisedValue arguments
2020/08/27 10:42:15 Failed to evaluate transaction: Failed to submit: Multiple errors occurred: - Transaction processing for endorser [localhost:9051]: Chaincode status Code: (500) UNKNOWN. Description: the asset asset13 already exists - Transaction processing for endorser [localhost:7051]: Chaincode status Code: (500) UNKNOWN. Description: the asset asset13 already exists
```
- Remove duplicated code of createAsset in asset-transfer-basic/application-go. ref: #291

Fix duplicated code: asset-transfer-basic/application-go

---

asset-transfer-sbe/README.md
asset-transfer-sbe/chaincode-java/src/main/java/org/hyperledger/fabric/samples/sbe/Asset.java
asset-transfer-sbe/chaincode-java/src/main/java/org/hyperledger/fabric/samples/sbe/AssetContract.java

Signed-off-by: Gaurav Giri <girigaurav@gmail.com>

Demonstrate NoutOf policies may be set for SBE (for Java Chaincode)

---

asset-transfer-secured-agreement/application-javascript/.eslintignore
asset-transfer-secured-agreement/application-javascript/.eslintrc.js
asset-transfer-secured-agreement/application-javascript/.gitignore
asset-transfer-secured-agreement/application-javascript/app.js
asset-transfer-secured-agreement/application-javascript/package.json
ci/scripts/run-test-network-secured.sh

Add the asset-transfer-secured-agreement javascript application
and have it run during CI.
Signed-off-by: Bret Harrison <beharrison@nc.rr.com>

Add secured agreement javascript application

---

chaincode/README.md

Update readme since the tutorials no longer use these smart contracts

Update chaincode readme table

---

chaincode/fabcar/javascript/package.json

Signed-off-by: Kestutis Gudynas <44440041+kemi04@users.noreply.github.com>

Dependencies updated

---

asset-transfer-basic/application-go/assetTransfer.go

[FAB-18236] The description of the error is incorrect. 
An error must be issued according to the transaction type.
* fix Error message
* add additional logs to transaction
Signed-off-by: KIM GEONWOO <kgw8919@gmail.com>

Fix Error message application-go

---

test-network/network.sh

Remove a stray instantiate in the comments
Signed-off-by: NIKHIL E GUPTA <ngupta@symbridge.com>

Remove instantiate comment

---

asset-transfer-sbe/README.md
asset-transfer-sbe/chaincode-java/src/main/java/org/hyperledger/fabric/samples/sbe/AssetContract.java
asset-transfer-sbe/chaincode-typescript/src/assetContract.ts

Signed-off-by: Gaurav Giri <girigaurav@gmail.com>

setStateBasedEndorsement NOutOf for typescript chaincode

---

asset-transfer-private-data/chaincode-go/META-INF/statedb/couchdb/collections/assetCollection/indexes/indexOwner.json

- field name should be 'objectType'

bugfix: asset type field name in couchdb index def

---

README.md

This change simply adds references to the two token samples to the README.

Add Token samples to README

---

token-account-based/chaincode-go/chaincode/token_contract.go

- New feature
- Added function that returns total supply of tokens in a token smart contract based on ERC-20 Token Standard
- [FAB-18275](https://jira.hyperledger.org/browse/FAB-18275)

Implemented TotalSupply function of ERC-20 Token Standard

---

ci/scripts/pullFabricImages.sh
test-network/addOrg3/docker/docker-compose-couch-org3.yaml
test-network/docker/docker-compose-couch.yaml

Update CouchDB in CI and test-network to 3.1.1.

Update CouchDB to 3.1.1

---

asset-transfer-events/application-javascript/.eslintignore
asset-transfer-events/application-javascript/.eslintrc.js
asset-transfer-events/application-javascript/.gitignore
asset-transfer-events/application-javascript/app.js
asset-transfer-events/application-javascript/package.json
asset-transfer-events/chaincode-javascript/.eslintignore
asset-transfer-events/chaincode-javascript/.eslintrc.js
asset-transfer-events/chaincode-javascript/.gitignore
asset-transfer-events/chaincode-javascript/index.js
asset-transfer-events/chaincode-javascript/lib/assetTransferEvents.js
asset-transfer-events/chaincode-javascript/package.json
asset-transfer-events/chaincode-javascript/test/assetTransferEvents.test.js
ci/azure-pipelines.yml
ci/scripts/run-test-network-events.sh
test-network/scripts/deployCC.sh

Add new chaincode and javascript application to demostrate
the use of events and events with private data.
Signed-off-by: Bret Harrison <beharrison@nc.rr.com>

Add Asset-Transfer-Events

---

asset-transfer-private-data/application-javascript/app.js

- assertions in js app, on reads, as smoke test for fabric PD, via az CI pipeline
- Improved readability of console out

Adding assertions in private data js app

---

token-account-based/chaincode-go/chaincode/token_contract.go

- New feature
- Improvement
- Added functionality that allows clients to approve other clients for a set allowance in which they can invoke withdrawal transactions up to. The Approve, Allowance, and TransferFrom functions are based on the ERC-20 Token Standard.
- [FAB-18275](https://jira.hyperledger.org/browse/FAB-18275)

Implemented Approve, Allowance, and TransferFrom of ERC-20

---

token-account-based/chaincode-go/chaincode/token_contract.go

- New feature
- Transfer and Approve functions of token_contract.go now emit chaincode events.
- [FAB-18275](https://jira.hyperledger.org/browse/FAB-18275)

Add Chaincode Events to Transfer and Approve

---

README.md

Update readme for auction sample

---

token-erc-20/chaincode-go/chaincode/token_contract.go

- New feature
- Added Burn function that grants the minter the ability to redeem tokens, decreasing the total token supply.
- Mint, Burn, and TransferFrom functions now emit chaincode events. 
- [FAB-18275](https://jira.hyperledger.org/browse/FAB-18275)

Add Burn Function and Events

---

asset-transfer-basic/application-javascript/app.js
asset-transfer-basic/application-typescript/src/app.ts
asset-transfer-events/application-javascript/app.js
asset-transfer-ledger-queries/application-javascript/app.js
asset-transfer-private-data/chaincode-java/src/main/java/org/hyperledger/fabric/samples/privatedata/AssetTransfer.java
asset-transfer-sbe/README.md
asset-transfer-sbe/application-javascript/app.js
asset-transfer-secured-agreement/application-javascript/app.js
test-network/scriptUtils.sh

- Improvement (improvement to code, performance, etc)
- Documentation update
- Short names are a crutch that can prevent someone from learning how to deploy their own chaincode. Short names have been replaced with their full path name.

Remove Short Names and Replace With Full Path in Samples

---

asset-transfer-basic/application-go/go.mod
fabcar/go/go.mod

Signed-off-by: andrew-coleman <andrew_coleman@uk.ibm.com>

FAB-18367 Update Go client samples to use RC1 of Go SDK

---

high-throughput/application-go/go.mod
high-throughput/application-go/go.sum

Move high throughput application to rc1 of GO SDK

---

test-network/scripts/createChannel.sh

Type of change
- Improvement 
Description
- Correct typing in script

correct typing

---

off_chain_data/startFabric.sh

As a response to the short names being removed

add full path to off-chain data sample

---

token-erc-20/chaincode-javascript/test/tokenERC20.test.js

Implement test code for SetOption.
Signed-off-by: Sol Kang <pdpxpd@gmail.com>

[FAB-18383] Add test code about SetOption in toeknERC20.test

---

test-network/configtx/configtx.yaml
test-network/docker/docker-compose-test-net.yaml
test-network/network.sh
test-network/scripts/createChannel.sh
test-network/scripts/envVar.sh

- Improvement (improvement to code, performance, etc)
- Update test network to use osadmin CLI for channel creation
- [FAB-18369](https://jira.hyperledger.org/browse/FAB-18369)

Update Test Network to use osadmin CLI for Channel Creation

---

auction/README.md
auction/application-javascript/bid.js
auction/application-javascript/closeAuction.js
auction/application-javascript/createAuction.js
auction/application-javascript/endAuction.js
auction/application-javascript/enrollAdmin.js
auction/application-javascript/queryAuction.js
auction/application-javascript/queryBid.js
auction/application-javascript/registerEnrollUser.js
auction/application-javascript/revealBid.js
auction/chaincode-go/smart-contract/auction.go
auction/chaincode-go/smart-contract/auctionQueries.go
auction/chaincode-go/smart-contract/utils.go

Some code cleanup for the auction sample
- Use base64 decoded identities
- use correct variable names
- re-use internal smart contract functions
- application code cleanup

Auction sample clean up

---

interest_rate_swaps/network/docker-compose.yaml

Signed-off-by: Brett Logan <lindluni@github.com>

Remove Stray IMAGE_TAG

---

commercial-paper/README.md
commercial-paper/network-starter.sh
commercial-paper/organization/digibank/configuration/cli/docker-compose.yml
commercial-paper/organization/magnetocorp/configuration/cli/docker-compose.yml
commercial-paper/organization/magnetocorp/configuration/cli/monitordocker.sh

Did a search in the Fabric repo. Replaced instance of `net_test` with `fabric_test`, which is the new test network name.
(Apologize for all the removed whitespace changes in the commercial-paper readme)

Update test network docker compose network name

---

asset-transfer-basic/chaincode-java/build.gradle
asset-transfer-events/chaincode-java/build.gradle
asset-transfer-private-data/chaincode-java/build.gradle
asset-transfer-sbe/chaincode-java/build.gradle
chaincode/fabcar/java/build.gradle

Signed-off-by: Kestutis Gudynas <44440041+kemi04@users.noreply.github.com>

Java chaincode samples fixed (FABCJ-300)

---

commercial-paper/organization/digibank/digibank.sh
commercial-paper/organization/magnetocorp/magnetocorp.sh

Replaces PR #434 
Signed-off-by: Kurt Seifried <kurt@seifried.org>
Signed-off-by: Ry Jones <ry@linux.com>

Fixed information leak

---

asset-transfer-basic/chaincode-external/.gitignore
asset-transfer-basic/chaincode-external/README.md
asset-transfer-basic/chaincode-external/assetTransfer.go
asset-transfer-basic/chaincode-external/chaincode1.env
asset-transfer-basic/chaincode-external/chaincode2.env
asset-transfer-basic/chaincode-external/docker-compose-chaincode.yaml

1. Modify the asset-transfer-basic chaincode example to run externally with TLS properties. Chaincode has an option to both run with/without TLS and make the decision at runtime using environment variables.
2. Add helper scripts/docker-compose files where necessary as a guide.
3. Add instructions to enable TLS properties on externally running chaincode.

TLS enabled external chaincode example

---

asset-transfer-basic/application-typescript-hsm/.gitignore
asset-transfer-basic/application-typescript-hsm/README.md
asset-transfer-basic/application-typescript-hsm/package.json
asset-transfer-basic/application-typescript-hsm/softhsm2.conf
asset-transfer-basic/application-typescript-hsm/src/app.ts
asset-transfer-basic/application-typescript-hsm/src/utils/AppUtil.ts
asset-transfer-basic/application-typescript-hsm/src/utils/CAUtil.ts
asset-transfer-basic/application-typescript-hsm/tsconfig.json
asset-transfer-basic/application-typescript-hsm/tslint.json
ci/azure-pipelines.yml
ci/scripts/run-test-network-basic.sh

Add a new sample in typescript to show how to use an HSM within a client node application

New HSM Typescript Sample

---

test-network/configtx/configtx.yaml

We dont need << as we are not adding or overwriting any values.
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

chore: minor simplification of configtx yaml

---

ci/azure-pipelines.yml
test-network/addOrg3/docker/docker-compose-ca-org3.yaml
test-network/addOrg3/docker/docker-compose-couch-org3.yaml
test-network/addOrg3/docker/docker-compose-org3.yaml
test-network/docker/docker-compose-ca.yaml
test-network/docker/docker-compose-couch.yaml
test-network/docker/docker-compose-test-net.yaml

Based on PR #449 by Brett Logan <lindluni@github.com>

Update Compose Spec & VM Spec Version

---

fabcar/java/pom.xml

Move to use the 1.4.5 rather than snapshot versions

---

asset-transfer-basic/chaincode-go/chaincode/smartcontract.go
asset-transfer-basic/chaincode-java/src/main/java/org/hyperledger/fabric/samples/assettransfer/AssetTransfer.java
asset-transfer-basic/chaincode-java/src/test/java/org/hyperledger/fabric/samples/assettransfer/AssetTransferTest.java
asset-transfer-basic/chaincode-javascript/lib/assetTransfer.js
asset-transfer-basic/chaincode-javascript/package.json
asset-transfer-basic/chaincode-typescript/package.json
asset-transfer-basic/chaincode-typescript/src/assetTransfer.ts

Show good praticse in order to make sure that data will be stored in the blockchain in a deterministic way using json

updated chaincodes for asset-transfer-basic in order to show good example on how achieving determinism over json

---

off_chain_data/.gitignore
off_chain_data/README.md
off_chain_data/blockProcessing.js
off_chain_data/config.json
off_chain_data/couchdbutil.js
off_chain_data/startFabric.sh

Stop supporting admin party mode with couchdb 3.1.1
Windows Git bash(MINGW*) fix for ./network down in startFabric.sh script
Signed-off-by: Indranil Majumder <indranil32@gmail.com>

changes to support couchdb 3.1.1

---

token-erc-1155/chaincode-go/chaincode/contract.go

Hi. I am the person who contributed ERC1155 in #463 . I noticed a problem with the chaincode. I fall into the trap of using map data structure in Go when developing a Fabric chaincode. The functions `BatchTransferFrom` and `BatchTransferFromMultiRecipient` in the ERC1155 chaincode sometimes give the error `ProposalResponsePayloads do not match`. This happens since iterating maps in Go is not deterministic. As a solution, I copied the keys of the map and sorted them and iterated over the sorted keys.
Signed-off-by: Baran Kılıç <baran.kilic@boun.edu.tr>

Fix ERC1155 chaincode indeterminism caused by iterating maps in Go

---

asset-transfer-basic/application-javascript/package.json
asset-transfer-basic/chaincode-javascript/package.json
asset-transfer-basic/chaincode-typescript/src/assetTransfer.ts
asset-transfer-events/application-javascript/package.json
asset-transfer-ledger-queries/application-javascript/package.json
asset-transfer-ledger-queries/chaincode-javascript/package.json
asset-transfer-sbe/application-javascript/package.json
asset-transfer-secured-agreement/application-javascript/package.json
auction-dutch/application-javascript/package.json
auction-simple/application-javascript/package.json
ci/azure-pipelines.yml
ci/scripts/lint.sh

- Removed global install of modules. 
- 
- Project can now chose it’s own linting framework, versions and execution pattern
- 
- Fixed linting errors for chaincode-typescript

Pipeline changes for Linting

---

test-network-k8s/network
test-network-k8s/scripts/application_connection.sh
test-network-k8s/scripts/utils.sh

- updated the logging for the application command; wasn't very good
- added some information to the help option. the current settings
useful if you're not sure what you've set
FYI @jkneubuh 

Updated logging

---

asset-transfer-basic/application-gateway-typescript/package.json
asset-transfer-basic/application-gateway-typescript/tsconfig.json

Signed-off-by: sapthasurendran <saptha.surendran@ibm.com>
Changed fabric-gateway version to unstable

Updated fabric-gateway version in application-gateway-typescript 

---

test-network-k8s/scripts/chaincode.sh

Get label for chaincode from metadata.json

---

asset-transfer-ledger-queries/application-javascript/app.js
asset-transfer-ledger-queries/application-javascript/package.json
asset-transfer-ledger-queries/chaincode-javascript/lib/asset_transfer_ledger_chaincode.js
chaincode/marbles02/javascript/marbles_chaincode.js

From issue #546 
Signed-off-by: David Faulstich Diniz Reis <davidfdr@gmail.com>

asset-transfer-ledger-queries/chaincode-javascript and chaincode/marbles02/javascript with pagination issues

---

token-erc-1155/README.md

Hi! I previously contributed ERC1155 in #463. I am now requested to add a acknowledgement text. I will be glad if you approve it. Thanks.
Signed-off-by: Baran Kılıç <baran.kilic@boun.edu.tr>

Add acknowledgement text for erc1155 chaincode

---

test-network-k8s/scripts/set_anchor_peer.sh
test-network/scripts/configUpdate.sh

Signed-off-by: sapthasurendran <saptha.surendran@ibm.com>
Fixed  issue  `configtxlator: error: open /dev/stdout: permission denied, try --help` found  while setting up test-network

Fixed configtxlator permission error

---

test-network/network.sh

Additionally, remove a trailing white space
Signed-off-by: Justin Yang <justin.yang@themedium.io>

test-network: Fix a indentation for readability

---

asset-transfer-basic/rest-api-typescript/README.md
asset-transfer-basic/rest-api-typescript/src/errors.ts
asset-transfer-basic/rest-api-typescript/src/index.ts

Move signposts to sample source files from index.ts to the readme and reinforce the key aspects of the sample

Update REST sample readme

---

asset-transfer-basic/application-gateway-typescript/package.json
ci/scripts/run-test-network-basic.sh

Added missing grpc dependency in package.json
Included migrated application in ci pipelines
Signed-off-by: sapthasurendran <saptha.surendran@ibm.com>

Bug fix in samples

---

test-network-k8s/README.md
test-network-k8s/scripts/prereqs.sh

New pull as per suggestion given on #581

Added 'jq' to prerequisite script and readme for k8s test network

---

test-network/prometheus-grafana/grafana/provisioning/dashboards/hlf-performances.json

Addresses some incorrect queries

Update the grafana dashboard

---

test-network/CHAINCODE_AS_A_SERVICE_TUTORIAL.md
test-network/README.md
test-network/prometheus-grafana/README.md
test-network/prometheus-grafana/docker-compose.yaml

Also fix the version of prometheus and grafana being used
to ensure the queries remain compatible as well as avoid
issues whether they may not work if latest images already
exist on machine but are not at a level that will work

Minor improvement to test network docs

---

asset-transfer-basic/rest-api-typescript/src/config.ts
asset-transfer-basic/rest-api-typescript/src/errors.ts
asset-transfer-basic/rest-api-typescript/src/fabric.ts
asset-transfer-basic/rest-api-typescript/src/jobs.ts
asset-transfer-basic/rest-api-typescript/src/redis.ts

Convert comments to tsdoc in REST sample

---

asset-transfer-basic/rest-api-typescript/package-lock.json
ci/azure-pipelines.yml
ci/templates/asset-transfer-basic/azure-pipelines-rest.yml

Build, test, and publish the REST server sample

Add REST sample to CI

---

asset-transfer-events/application-gateway-typescript/.eslintrc.json
asset-transfer-events/application-gateway-typescript/package.json
asset-transfer-events/application-gateway-typescript/src/app.ts

Changed:
- Console output formatting
- Transaction arguments
- Readability and comments of code
- Linting rules
- Missing semicolons

Fixes to TypeScript asset-transfer-events to match Go sample

---

asset-transfer-basic/rest-api-typescript/README.md
asset-transfer-basic/rest-api-typescript/docker-compose.yaml
test-network-k8s/README.md
test-network-k8s/docs/APPLICATIONS.md
test-network-k8s/kube/fabric-rest-sample.yaml
test-network-k8s/scripts/rest_sample.sh

Update samples to use published fabric-rest-sample

---

asset-transfer-basic/rest-api-typescript/README.md
asset-transfer-basic/rest-api-typescript/docker-compose.yaml
asset-transfer-basic/rest-api-typescript/package.json

Update REST sample with Redis password

---

test-network/README.md

Podman experimental and not native MacOs

---

asset-transfer-basic/rest-api-typescript/README.md

Add that one needs to have the ledger initialized for the sample to
work.

Improve REST sample README

---

ci/scripts/run-test-network-basic.sh
test-network/addOrg3/addOrg3.sh
test-network/addOrg3/compose/docker/docker-compose-org3.yaml
test-network/network.sh

Also added testing addOrg3 to build pipeline
closes #664 

fix addOrg3 for test network

---

asset-transfer-private-data/README.md
asset-transfer-private-data/application-gateway-typescript/.eslintrc.json
asset-transfer-private-data/application-gateway-typescript/.gitignore
asset-transfer-private-data/application-gateway-typescript/README.md
asset-transfer-private-data/application-gateway-typescript/package.json
asset-transfer-private-data/application-gateway-typescript/src/app.ts
asset-transfer-private-data/application-gateway-typescript/src/connect.ts
asset-transfer-private-data/application-gateway-typescript/tsconfig.json
ci/scripts/run-test-network-private.sh

Signed-off-by: sapthasurendran <saptha.surendran@ibm.com>

Private data samples migration

---

asset-transfer-basic/chaincode-javascript/lib/assetTransfer.js

only broken in main branch, not in release-2.2

fix chaincode breakage in asset-transfer-basic

---

asset-transfer-basic/rest-api-typescript/package-lock.json
asset-transfer-basic/rest-api-typescript/package.json
asset-transfer-basic/rest-api-typescript/src/server.ts

After feedback from the community, this PR adds CORS support in, but as an option
to enable.
Along with warnings that the default wildcard origin might not be applicable
in a production use case

CORS Enablement

---

asset-transfer-basic/rest-api-typescript/README.md
test-network-k8s/docs/CA.md
test-network-k8s/docs/CHANNELS.md
test-network-k8s/docs/HIGH_AVAILABILITY.md

Signed-off-by: Tatsuya Sato <tatsuya.sato.so@hitachi.com>

Fix typos and broken links in docs

---

test-network/scripts/deployCC.sh

fix error message in deployCC

---

token-erc-1155/README.md
token-erc-1155/chaincode-go/chaincode/contract.go
token-erc-20/README.md
token-erc-20/chaincode-go/chaincode/token_contract.go
token-erc-20/chaincode-javascript/test/tokenERC20.test.js
token-erc-721/README.md
token-erc-721/chaincode-go/chaincode/erc721-contract.go
token-utxo/README.md
token-utxo/chaincode-go/chaincode/token_contract.go

- added a final fix to the go contract check for overflow
- added documentation for initialization of the contract in the READMEs
- include typos and idiomatic code fixes highlighted from comments of the last pr

ERC token samples: Added final fixes to erc token samples and documentation

---

asset-transfer-basic/application-go/assetTransfer.go
asset-transfer-basic/chaincode-go/chaincode/smartcontract.go

Signed-off-by: Tommy TIAN <xtianae@connect.ust.hk>

Fix typo in asset-transfer-basic

---

asset-transfer-secured-agreement/README.md
asset-transfer-secured-agreement/application-gateway-typescript/src/app.ts
asset-transfer-secured-agreement/application-gateway-typescript/src/contractWrapper.ts
asset-transfer-secured-agreement/application-javascript/app.js
asset-transfer-secured-agreement/chaincode-go/asset_transfer.go

Updated and Improved asset-transfer-secured-agreement sample

---

off_chain_data/README.md
off_chain_data/application-java/app/build.gradle
off_chain_data/application-java/app/src/main/java/Connections.java

Also use hyperlinks for easier navigation to code mentioned in the README.

Use new default call options API in Java off_chain_data sample

---

token-erc-20/chaincode-javascript/lib/tokenERC20.js
token-erc-721/chaincode-javascript/lib/tokenERC721.js

Signed-off-by: Rajat Sharma <connecttorajat@outlook.com>

ERC:721 Check for Intitialized changed

---

token-erc-1155/chaincode-go/chaincode/contract.go
token-erc-20/chaincode-go/chaincode/token_contract.go

This resolves issue #765.
Signed-off-by: Rajat Sharma <connecttorajat@outlook.com>

ERC1155: subtraction overflow issue resolved

---

token-erc-1155/README.md
token-erc-20/README.md
token-erc-20/chaincode-java/settings.gradle
token-erc-721/README.md
token-erc-721/chaincode-java/settings.gradle
token-utxo/README.md

tokens docs fix update + small fix to erc721 and erc 20 java chaincode gradle.settings
Closes #762 

token samples: added fixes to documentation and readmes 

---

test-network-k8s/docs/APPLICATIONS.md
test-network-k8s/docs/CHAINCODE.md

This patch fixes errors in the document.
Fix errors as follows:
- Change shell script arguments
- Correct display results
Signed-off-by: Satoshi Ito <satoshi.ito.tf@hitachi.com>

Fix test-network-k8s docs

---

asset-transfer-basic/chaincode-typescript/.dockerignore
asset-transfer-basic/chaincode-typescript/Dockerfile

- Add options to stop permission issue with the npm cache (podman is quite strict here)
- Add in platform for tini

Update Node.js dockerfile

---

token-erc-1155/chaincode-go/chaincode/contract.go

Signed-off-by: Stefan Obermeier <st.obermeier@seeburger.de>

use existing const instead of local string

---

test-network/scripts/ccutils.sh
test-network/scripts/deployCC.sh
test-network/scripts/deployCCAAS.sh

Correctly check for installed chaincode and enable the same chaincode to be deployed on different channels

Fix test network chaincode deploy

---

test-network-k8s/docs/CHAINCODE.md
test-network-k8s/docs/KUBERNETES.md
test-network-k8s/scripts/cluster.sh
test-network-k8s/scripts/fabric_config.sh

This patch fixes some minor improvement points that I found on test-network-k8s.
Signed-off-by: Tatsuya Sato <tatsuya.sato.so@hitachi.com>

Minor fixes and improvements to test-network-k8s

---

test-network/addOrg3/compose/docker/peercfg/core.yaml
test-network/addOrg3/compose/podman/peercfg/core.yaml
test-network/compose/docker/peercfg/core.yaml
test-network/compose/podman/peercfg/core.yaml

Remove mistaken msp path

---

test-network-k8s/kube/org1/org1-peer1.yaml
test-network-k8s/kube/org2/org2-peer1.yaml

This patch fixes the ingress setting so that the peer-gateway works correctly.
Signed-off-by: Satoshi Ito <satoshi.ito.tf@hitachi.com>

Minor fixes to the ingress setting

---

test-network/scripts/deployCC.sh

Added a check for prerequisites into deployCC script.  
Issue: https://github.com/hyperledger/fabric/issues/3848
Signed-off-by: Parameswaran Selvam <parselva@in.ibm.com>

added a check for prereq into deploycc script

---

full-stack-asset-transfer-guide/docs/CloudReady/13-kube-public-cloud.md

Signed-off-by: Ramesh M <62267259+ramdisk-ott@users.noreply.github.com>

Full stack asset transfer deplyment in Digital ocean kubernetes cluster

---

asset-transfer-sbe/chaincode-typescript/src/assetContract.ts

The old way used the direct protobuf functions, there is a helper function in the chaincode does exactly that.

Swap to use the Helper Function to create policies

---

.github/actions/test-network-setup/action.yaml
.github/workflows/lint.yaml
.github/workflows/rest-sample.yaml
.github/workflows/test-fsat.yaml
.github/workflows/test-network-basic.yaml
.github/workflows/test-network-events.yaml
.github/workflows/test-network-gateway.yaml
.github/workflows/test-network-hsm.yaml
.github/workflows/test-network-k8s.yaml
.github/workflows/test-network-ledger.yaml
.github/workflows/test-network-off-chain.yaml
.github/workflows/test-network-private.yaml
.github/workflows/test-network-sbe.yaml
.github/workflows/test-network-secured.yaml
asset-transfer-sbe/chaincode-typescript/package.json
asset-transfer-sbe/chaincode-typescript/src/assetContract.ts

Runs the fabric-samples test suites with Fabric 2.5 images and binaries.

run test suites with 2.5 binaries and images

---

hardware-security-module/application-go/hsm-sample.go

Fix go lint issue by running goimports.

Fix go lint issue

---

asset-transfer-basic/application-go/assetTransfer.go
asset-transfer-basic/application-java/src/main/java/application/java/App.java
asset-transfer-basic/application-java/src/main/java/application/java/EnrollAdmin.java
asset-transfer-basic/application-java/src/main/java/application/java/RegisterUser.java
asset-transfer-basic/application-javascript/app.js
asset-transfer-basic/application-javascript/package.json
asset-transfer-basic/application-typescript-hsm/src/app.ts
asset-transfer-basic/application-typescript/package.json
asset-transfer-basic/application-typescript/src/app.ts
asset-transfer-basic/application-typescript/src/utils/AppUtil.ts
ci/scripts/run-test-network-basic.sh
full-stack-asset-transfer-guide/justfile

- Application failure should result in CI failure (exit code 1)
- Automatically remove wallet from prior runs 
- Fix chaincode name issues, allow chaincode name to be passed from CI
- Fix appUser collisions (duplicate registration failures)
- Fix key create collisions across apps (in cases where same chaincode is used for multiple apps)

asset-transfer-basic CI improvements

---

off_chain_data/legacy-application-javascript/README.md
test-network-nano-bash/peer1.sh
test-network-nano-bash/peer2.sh
test-network-nano-bash/peer3.sh
test-network-nano-bash/peer4.sh
test-network/addOrg3/compose/compose-couch-org3.yaml
test-network/addOrg3/compose/podman/podman-compose-couch-org3.yaml
test-network/compose/compose-couch.yaml

Bump couchdb to 3.2.2

---

ci/scripts/run-test-network-basic.sh
ci/scripts/run-test-network-gateway.sh

Add debug logging to CI scripts.

Add debug logging to CI scripts

---

.github/workflows/lint.yaml
.github/workflows/rest-sample.yaml
.github/workflows/test-fsat.yaml
.github/workflows/test-network-basic.yaml
.github/workflows/test-network-events.yaml
.github/workflows/test-network-gateway.yaml
.github/workflows/test-network-hsm.yaml
.github/workflows/test-network-k8s.yaml
.github/workflows/test-network-ledger.yaml
.github/workflows/test-network-off-chain.yaml
.github/workflows/test-network-private.yaml
.github/workflows/test-network-sbe.yaml
.github/workflows/test-network-secured.yaml

Cancel existing workflows on subsequent PR push.

Cancel existing workflows on subsequent PR push

---

.github/workflows/lint.yaml
.github/workflows/rest-sample.yaml
.github/workflows/test-fsat.yaml
.github/workflows/test-network-basic.yaml
.github/workflows/test-network-events.yaml
.github/workflows/test-network-gateway.yaml
.github/workflows/test-network-hsm.yaml
.github/workflows/test-network-k8s.yaml
.github/workflows/test-network-ledger.yaml
.github/workflows/test-network-off-chain.yaml
.github/workflows/test-network-private.yaml
.github/workflows/test-network-sbe.yaml
.github/workflows/test-network-secured.yaml

Signed-off-by: Ry Jones <ry@linux.com>

chore(ci): use dedicated Fabric runners

---

token-erc-1155/README.md

Instructions to setup the environment aren't quite right. This fixes it.

Fix erc-1155 sample README

---

full-stack-asset-transfer-guide/infrastructure/sample-network/network
test-network-nano-bash/peer1.sh
test-network-nano-bash/peer2.sh
test-network-nano-bash/peer3.sh
test-network-nano-bash/peer4.sh
test-network/addOrg3/compose/compose-couch-org3.yaml
test-network/addOrg3/compose/podman/podman-compose-couch-org3.yaml
test-network/compose/compose-couch.yaml

Bump CouchDB to 3.3.2

---

.github/actions/fsat-setup/action.yaml
.github/actions/test-network-setup/action.yaml

Update CI to use Fabric v2.5.1.

Update CI to Fabric v2.5.1

---

asset-transfer-private-data/README.md
asset-transfer-private-data/chaincode-typescript/.dockerignore
asset-transfer-private-data/chaincode-typescript/.gitignore
asset-transfer-private-data/chaincode-typescript/Dockerfile
asset-transfer-private-data/chaincode-typescript/Readme.md
asset-transfer-private-data/chaincode-typescript/collections_config.json
asset-transfer-private-data/chaincode-typescript/docker/docker-entrypoint.sh
asset-transfer-private-data/chaincode-typescript/npm-shrinkwrap.json
asset-transfer-private-data/chaincode-typescript/package.json
asset-transfer-private-data/chaincode-typescript/src/asset.ts
asset-transfer-private-data/chaincode-typescript/src/assetTransfer.ts
asset-transfer-private-data/chaincode-typescript/src/assetTransferDetails.ts
asset-transfer-private-data/chaincode-typescript/src/assetTransferTransientInput.ts
asset-transfer-private-data/chaincode-typescript/src/index.ts
asset-transfer-private-data/chaincode-typescript/src/transferAgreement.ts
asset-transfer-private-data/chaincode-typescript/tsconfig.json
asset-transfer-private-data/chaincode-typescript/tslint.json

Hi,
I added a typescript implementation of private data chaincode. I tested it with the private data tutorial (https://hyperledger-fabric.readthedocs.io/en/latest/private_data_tutorial.html) and everything works fine.
I can make changes, etc., if needed.
Kind regards

Add private data chaincode-typescript

---

test-network-nano-bash/README.md
test-network-nano-bash/chaincode_interaction.sh
test-network-nano-bash/install&approve&commit_chaincode_peer1.sh

- Use calculatepackageid to set CHAINCODE_ID
- Use waitForEvent to wait for commit event intead of 2s sleep

test-network-nano-bash chaincode id and waitForEvent improvements

---

test-network-nano-bash/.gitignore
test-network-nano-bash/README.md

- Fix typos
- Update gitignore

Minor improvements on test-network-nano-bash

---

full-stack-asset-transfer-guide/README.md
full-stack-asset-transfer-guide/docs/SmartContractDev/00-Introduction-ES.md
full-stack-asset-transfer-guide/docs/SmartContractDev/00-Introduction.md
full-stack-asset-transfer-guide/docs/SmartContractDev/01-Exercise-Getting-Started-ES.md
full-stack-asset-transfer-guide/docs/SmartContractDev/01-Exercise-Getting-Started.md
full-stack-asset-transfer-guide/docs/SmartContractDev/02-Exercise-Adding-tx-function-ES.md
full-stack-asset-transfer-guide/docs/SmartContractDev/03-Test-And-Debug-Reference-ES.md
full-stack-asset-transfer-guide/docs/SmartContractDev/03-Test-And-Debug-Reference.md

This is the translation into spanish of the samples documentation in the Full Stack Asset Transfer sample for the Smart Contract Development unit. Included also in this PR are update to the Readme so user can access the translated pages as well as minor corrections to the English pages.

Smart Contract Dev Spanish Translation - FullStackAssetTransfer

---

test-network-nano-bash/ca/ca_utils.sh
test-network-nano-bash/external_builders/golang/bin/run
test-network-nano-bash/external_builders/node/bin/run

- Correct sh compability in ca_utils.sh
- Correct linux compatibility in external builder

Add chaincode logging for binary chaincode in test-network-nano-bash

---

SECURITY.md
test-network/prometheus-grafana/README.md

Quotation marks are used incorrectly.

docs: Quotation marks are used incorrectly.

---

.github/settings.yml
CODEOWNERS
CODE_OF_CONDUCT.md
SECURITY.md

- Bug fix
- Documentation update
This PR updates some links.
https://github.com/hyperledger/fabric/issues/5092
https://github.com/hyperledger/fabric/pull/5093

Update some old links

---

full-stack-asset-transfer-guide/infrastructure/sample-network/network
test-network-k8s/network
test-network-nano-bash/peer1.sh
test-network-nano-bash/peer2.sh
test-network-nano-bash/peer3.sh
test-network-nano-bash/peer4.sh
test-network/addOrg3/compose/compose-couch-org3.yaml
test-network/addOrg3/compose/podman/podman-compose-couch-org3.yaml
test-network/compose/compose-couch.yaml

Bump couchdb to 3.4.2
